#!/usr/bin/env python3
"""
SCRIPT 05 — BUILD CMAUP 40D SIMILARITY REFERENCE / INDEX

Purpose
-------
Build the reusable similarity reference for the exact 40-dimensional
Model-1 representation generated by Script 04.

Design principles
-----------------
1. The Script-04 40D reference is authoritative.
2. No target labels, target annotations, or activity labels are used to
   construct the similarity representation.
3. 40D standardization is FIT ON TRAIN ONLY and then applied unchanged to
   train + test/reference.
4. No new imputation is performed.
5. No new molecular/3D/MoLFormer features are generated.
6. Morgan/ECFP is retained only as an independent 2D comparator.
7. The primary similarity is cosine similarity in the standardized 40D
   feature space.
8. The script creates provenance, QC, and reusable artifacts for Script 06+.
9. This script does NOT train a target model and does NOT infer targets.

Expected execution
------------------
Place this file directly under:
    /lustre/home/sklab202/sourav/PULP/

Then run:
    /lustre/home/sklab202/miniconda3/envs/PULP/bin/python 05_build_cmaup_40d_similarity_index.py

Output directory:
    target_model/similarity/05_cmaup_40d_similarity/
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import platform
import sys
import time
from datetime import datetime
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from rdkit import Chem, DataStructs, rdBase
from rdkit.Chem import AllChem
from sklearn.neighbors import NearestNeighbors


# ============================================================================
# 0. PATHS / CONSTANTS
# ============================================================================

PULP_DIR = Path(__file__).resolve().parent

INPUT_DIR = PULP_DIR / "target_model" / "feature_space" / "04_cmaup_40d_reference"
OUTPUT_DIR = PULP_DIR / "target_model" / "similarity" / "05_cmaup_40d_similarity"

REFERENCE_FILE = INPUT_DIR / "cmaup_40d_reference.tsv"
REFERENCE_MATRIX_FILE = INPUT_DIR / "cmaup_40d_feature_matrix.tsv"
REFERENCE_ID_MATRIX_FILE = INPUT_DIR / "cmaup_40d_id_feature_matrix.tsv"
MANIFEST_FILE = INPUT_DIR / "validated_40_feature_manifest.tsv"
SCRIPT04_MANIFEST = INPUT_DIR / "04_cmaup_40d_reference_manifest.json"
SCRIPT04_QC = INPUT_DIR / "04_cmaup_40d_reference_qc.tsv"

FINAL_40_MANIFEST = (
    PULP_DIR
    / "feature_engineering"
    / "model_development"
    / "tables"
    / "table_03_final_40_feature_manifest.tsv"
)

TRAIN_SPLIT = PULP_DIR / "feature_engineering" / "split" / "train_80.tsv"
TEST_SPLIT = PULP_DIR / "feature_engineering" / "split" / "test_20.tsv"

RANDOM_STATE = 42

# Independent 2D comparator:
MORGAN_RADIUS = 2
MORGAN_NBITS = 2048
MORGAN_CHUNK_SIZE = 10000

# Primary 40D retrieval index:
# Cosine distance = 1 - cosine similarity.
NEIGHBOR_COUNT = 50

EXPECTED_REFERENCE_ROWS = 60190
EXPECTED_TRAIN_ROWS = 48152
EXPECTED_TEST_ROWS = 12038
EXPECTED_FEATURE_COUNT = 40
EXPECTED_MOLFORMER_DIM = 768

EXPECTED_MOLECULAR_FEATURES = [
    "FractionCSP3",
    "SPS",
    "NumAtomStereoCenters",
    "SMR_VSA5",
    "BCUT2D_MRLOW",
    "BCUT2D_CHGLO",
    "VSA_EState6",
    "NumAromaticRings",
    "SMR_VSA7",
    "fr_Al_OH",
]

EXPECTED_3D_FEATURES = [
    "PBF",
    "SpherocityIndex",
    "PMI1",
    "InertialShapeFactor",
    "PMI2",
    "NPR2",
    "RadiusOfGyration",
    "Eccentricity",
    "NPR1",
]

EXPECTED_MOLFORMER_FEATURES = [
    "molformer_0279",
    "molformer_0491",
    "molformer_0407",
    "molformer_0047",
    "molformer_0230",
    "molformer_0638",
    "molformer_0393",
    "molformer_0129",
    "molformer_0659",
    "molformer_0747",
    "molformer_0298",
    "molformer_0742",
    "molformer_0177",
    "molformer_0119",
    "molformer_0400",
    "molformer_0367",
    "molformer_0485",
    "molformer_0536",
    "molformer_0418",
    "molformer_0455",
    "molformer_0312",
]

EXPECTED_FEATURE_ORDER = (
    EXPECTED_MOLECULAR_FEATURES
    + EXPECTED_3D_FEATURES
    + EXPECTED_MOLFORMER_FEATURES
)


# ============================================================================
# 1. OUTPUT FILES
# ============================================================================

OUTPUT_FILES = {
    "standardized_matrix": OUTPUT_DIR / "cmaup_40d_standardized_matrix.tsv",
    "standardized_id_matrix": OUTPUT_DIR / "cmaup_40d_standardized_id_matrix.tsv",
    "train_standardized_matrix": OUTPUT_DIR / "cmaup_40d_standardized_train.tsv",
    "test_standardized_matrix": OUTPUT_DIR / "cmaup_40d_standardized_test.tsv",
    "standardization_parameters": OUTPUT_DIR / "40d_standardization_parameters.tsv",
    "cosine_neighbor_index": OUTPUT_DIR / "cmaup_40d_cosine_neighbor_index.joblib",
    "cosine_neighbor_ids": OUTPUT_DIR / "cmaup_40d_train_top50_neighbors.tsv",
    "morgan_fingerprints": OUTPUT_DIR / "cmaup_morgan_ecfp4_2048_packed.npz",
    "morgan_metadata": OUTPUT_DIR / "cmaup_morgan_ecfp4_2048_metadata.tsv",
    "morgan_qc": OUTPUT_DIR / "morgan_ecfp4_qc.tsv",
    "input_provenance": OUTPUT_DIR / "input_provenance.tsv",
    "feature_manifest": OUTPUT_DIR / "validated_40_feature_manifest.tsv",
    "reference_alignment_qc": OUTPUT_DIR / "reference_alignment_qc.tsv",
    "standardization_qc": OUTPUT_DIR / "standardization_qc.tsv",
    "similarity_qc": OUTPUT_DIR / "similarity_qc.tsv",
    "neighbor_qc": OUTPUT_DIR / "neighbor_index_qc.tsv",
    "run_manifest": OUTPUT_DIR / "05_cmaup_40d_similarity_manifest.json",
    "qc_text": OUTPUT_DIR / "05_cmaup_40d_similarity_qc.txt",
}


# ============================================================================
# 2. HELPERS
# ============================================================================

RUN_START = datetime.now().astimezone()


def now_iso() -> str:
    return datetime.now().astimezone().isoformat()


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            chunk = fh.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def require_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"REQUIRED INPUT MISSING: {label}: {path}")
    if not path.is_file():
        raise RuntimeError(f"INPUT IS NOT A FILE: {label}: {path}")


def write_tsv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, sep="\t", index=False)


def finite_array_qc(x: np.ndarray) -> tuple[int, int, int]:
    arr = np.asarray(x)
    nan_count = int(np.isnan(arr).sum())
    inf_count = int(np.isinf(arr).sum())
    nonfinite = nan_count + inf_count
    return nan_count, inf_count, nonfinite


def status(ok: bool, warn: bool = False) -> str:
    if ok:
        return "PASS"
    if warn:
        return "WARN"
    return "FAIL"


def log_section(number: int, title: str) -> None:
    print("\n" + "=" * 78)
    print(f"{number}. {title}")
    print("=" * 78)


def parse_feature_columns(df: pd.DataFrame) -> list[str]:
    missing = [f for f in EXPECTED_FEATURE_ORDER if f not in df.columns]
    if missing:
        raise RuntimeError(
            "The Script-04 reference is missing expected 40D features:\n"
            + "\n".join(missing)
        )
    return EXPECTED_FEATURE_ORDER.copy()


def load_manifest_features(path: Path) -> list[str]:
    df = pd.read_csv(path, sep="\t", dtype=str)

    # The Script-04 validated manifest is expected to contain Feature_Name.
    possible = [
        c for c in df.columns
        if c.lower() in {
            "feature_name",
            "feature",
            "feature_name_40d",
            "name",
        }
    ]

    if not possible:
        raise RuntimeError(
            f"Cannot identify feature-name column in manifest: {path}\n"
            f"Columns: {list(df.columns)}"
        )

    feature_col = possible[0]
    features = [str(x).strip() for x in df[feature_col].tolist() if str(x).strip()]

    if len(features) != EXPECTED_FEATURE_COUNT:
        raise RuntimeError(
            f"Validated manifest contains {len(features)} features; "
            f"expected {EXPECTED_FEATURE_COUNT}."
        )

    if features != EXPECTED_FEATURE_ORDER:
        raise RuntimeError(
            "Validated Script-04 feature order differs from the locked "
            "40-feature order.\n"
            f"Expected: {EXPECTED_FEATURE_ORDER}\n"
            f"Observed: {features}"
        )

    return features


def validate_split_file(path: Path, expected_rows: int, split_name: str) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t", dtype=str)

    if "np_id" not in df.columns:
        raise RuntimeError(f"{split_name}: missing np_id column: {path}")

    if len(df) != expected_rows:
        raise RuntimeError(
            f"{split_name}: expected {expected_rows} rows, observed {len(df)}."
        )

    ids = df["np_id"].astype(str).str.strip()

    if ids.isna().any() or (ids == "").any():
        raise RuntimeError(f"{split_name}: missing/blank np_id detected.")

    if ids.duplicated().any():
        raise RuntimeError(f"{split_name}: duplicate np_id detected.")

    return df


def make_morgan_fp(smiles: str):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return AllChem.GetMorganFingerprintAsBitVect(
        mol,
        radius=MORGAN_RADIUS,
        nBits=MORGAN_NBITS,
    )


def bitvect_to_packed(fp) -> np.ndarray:
    # RDKit bit ordering is preserved by DataStructs.BitVectToBinaryText.
    raw = DataStructs.BitVectToBinaryText(fp)
    return np.frombuffer(raw, dtype=np.uint8).copy()


def packed_to_bit_count(packed: np.ndarray) -> np.ndarray:
    return np.unpackbits(packed, axis=1).sum(axis=1).astype(np.int16)


def cosine_similarity_self_check(x: np.ndarray) -> tuple[float, float, float]:
    # x is expected to be row-normalized.
    norms = np.linalg.norm(x, axis=1)
    return float(norms.min()), float(norms.max()), float(np.mean(norms))


# ============================================================================
# 3. PREPARE OUTPUT DIRECTORY
# ============================================================================

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 78)
print("SCRIPT 05 — CMAUP 40D SIMILARITY REFERENCE / INDEX")
print("=" * 78)
print(f"PULP directory : {PULP_DIR}")
print(f"Output directory : {OUTPUT_DIR}")
print(f"Start time : {RUN_START.isoformat()}")
print(f"Python : {sys.version.split()[0]}")
print(f"NumPy : {np.__version__}")
print(f"pandas : {pd.__version__}")
print(f"RDKit : {rdBase.rdkitVersion}")
print()


# ============================================================================
# 4. INPUT FILE CHECK
# ============================================================================

log_section(1, "INPUT FILE CHECK")

required_inputs = {
    "script04_reference": REFERENCE_FILE,
    "script04_feature_matrix": REFERENCE_MATRIX_FILE,
    "script04_id_feature_matrix": REFERENCE_ID_MATRIX_FILE,
    "script04_validated_manifest": MANIFEST_FILE,
    "script04_manifest_json": SCRIPT04_MANIFEST,
    "script04_qc": SCRIPT04_QC,
    "final_40_feature_manifest": FINAL_40_MANIFEST,
    "train_split": TRAIN_SPLIT,
    "test_split": TEST_SPLIT,
}

input_provenance_rows = []

for label, path in required_inputs.items():
    require_file(path, label)
    digest = sha256_file(path)
    size = path.stat().st_size

    print(f"FOUND: {path.relative_to(PULP_DIR)}")
    print(f"SHA256: {digest}")

    input_provenance_rows.append(
        {
            "input_label": label,
            "path": str(path.relative_to(PULP_DIR)),
            "exists": True,
            "size_bytes": int(size),
            "sha256": digest,
            "required": True,
        }
    )

write_tsv(
    pd.DataFrame(input_provenance_rows),
    OUTPUT_FILES["input_provenance"],
)


# ============================================================================
# 5. VALIDATE SCRIPT-04 MANIFEST
# ============================================================================

log_section(2, "VALIDATING LOCKED 40-FEATURE MANIFEST")

validated_features = load_manifest_features(MANIFEST_FILE)

print(f"Molecular features : {len(EXPECTED_MOLECULAR_FEATURES)}")
print(f"3D-QSAR features   : {len(EXPECTED_3D_FEATURES)}")
print(f"MoLFormer features : {len(EXPECTED_MOLFORMER_FEATURES)}")
print(f"Total features     : {len(validated_features)}")

write_tsv(
    pd.DataFrame(
        {
            "feature_order": np.arange(1, 41),
            "feature_name": validated_features,
            "feature_family": (
                ["Molecular"] * 10
                + ["3D-QSAR"] * 9
                + ["MoLFormer"] * 21
            ),
        }
    ),
    OUTPUT_FILES["feature_manifest"],
)


# ============================================================================
# 6. LOAD SCRIPT-04 REFERENCE
# ============================================================================

log_section(3, "LOADING SCRIPT-04 CMAUP 40D REFERENCE")

reference = pd.read_csv(
    REFERENCE_FILE,
    sep="\t",
    low_memory=False,
)

print(f"Reference rows    : {len(reference):,}")
print(f"Reference columns : {len(reference.columns):,}")

if len(reference) != EXPECTED_REFERENCE_ROWS:
    raise RuntimeError(
        f"Expected {EXPECTED_REFERENCE_ROWS} Script-04 reference rows; "
        f"observed {len(reference)}."
    )

if "np_id" not in reference.columns:
    raise RuntimeError("Script-04 reference lacks np_id.")

reference["np_id"] = reference["np_id"].astype(str).str.strip()

if reference["np_id"].duplicated().any():
    dup_count = int(reference["np_id"].duplicated().sum())
    raise RuntimeError(f"Duplicate np_id values in Script-04 reference: {dup_count}")

feature_cols = parse_feature_columns(reference)

missing_feature_cols = [c for c in feature_cols if c not in reference.columns]
if missing_feature_cols:
    raise RuntimeError(
        "Missing 40D feature columns:\n" + "\n".join(missing_feature_cols)
    )

X_reference = reference[feature_cols].apply(pd.to_numeric, errors="coerce").to_numpy(
    dtype=np.float64
)

nan_count, inf_count, nonfinite = finite_array_qc(X_reference)

print(f"40D reference NaN : {nan_count}")
print(f"40D reference Inf : {inf_count}")

if nonfinite != 0:
    raise RuntimeError(
        "Script-04 reference contains NaN/Inf in the final 40D representation. "
        "Do not continue until Script 04 is corrected."
    )


# ============================================================================
# 7. VALIDATE TRAIN / TEST ALIGNMENT
# ============================================================================

log_section(4, "VALIDATING TRAIN/TEST ALIGNMENT")

train = validate_split_file(TRAIN_SPLIT, EXPECTED_TRAIN_ROWS, "TRAIN")
test = validate_split_file(TEST_SPLIT, EXPECTED_TEST_ROWS, "TEST")

train_ids = set(train["np_id"].astype(str))
test_ids = set(test["np_id"].astype(str))
reference_ids = set(reference["np_id"].astype(str))

overlap = train_ids.intersection(test_ids)
union = train_ids.union(test_ids)

if overlap:
    raise RuntimeError(
        f"Train/test overlap detected: {len(overlap)} IDs."
    )

if len(union) != EXPECTED_REFERENCE_ROWS:
    raise RuntimeError(
        f"Train/test union expected {EXPECTED_REFERENCE_ROWS}; observed {len(union)}."
    )

missing_from_reference = union - reference_ids
extra_in_reference = reference_ids - union

print(f"TRAIN rows : {len(train):,}")
print(f"TEST rows  : {len(test):,}")
print(f"Union      : {len(union):,}")
print(f"Train/test overlap : {len(overlap)}")
print(f"IDs missing from reference : {len(missing_from_reference)}")
print(f"Reference IDs outside split union : {len(extra_in_reference)}")

if missing_from_reference or extra_in_reference:
    raise RuntimeError("Reference/split ID alignment failed.")

reference_split = pd.Series(
    np.where(
        reference["np_id"].isin(train_ids),
        "TRAIN",
        np.where(reference["np_id"].isin(test_ids), "TEST", "UNKNOWN"),
    ),
    index=reference.index,
    name="split",
)

if (reference_split == "UNKNOWN").any():
    raise RuntimeError("UNKNOWN split assignment found in reference.")

reference["split"] = reference_split

write_tsv(
    pd.DataFrame(
        [
            {
                "check": "train_rows",
                "expected": EXPECTED_TRAIN_ROWS,
                "observed": len(train),
                "status": status(len(train) == EXPECTED_TRAIN_ROWS),
            },
            {
                "check": "test_rows",
                "expected": EXPECTED_TEST_ROWS,
                "observed": len(test),
                "status": status(len(test) == EXPECTED_TEST_ROWS),
            },
            {
                "check": "train_test_overlap",
                "expected": 0,
                "observed": len(overlap),
                "status": status(len(overlap) == 0),
            },
            {
                "check": "reference_rows",
                "expected": EXPECTED_REFERENCE_ROWS,
                "observed": len(reference),
                "status": status(len(reference) == EXPECTED_REFERENCE_ROWS),
            },
            {
                "check": "reference_ids_missing_from_split_union",
                "expected": 0,
                "observed": len(missing_from_reference),
                "status": status(len(missing_from_reference) == 0),
            },
            {
                "check": "reference_extra_ids",
                "expected": 0,
                "observed": len(extra_in_reference),
                "status": status(len(extra_in_reference) == 0),
            },
        ]
    ),
    OUTPUT_FILES["reference_alignment_qc"],
)


# ============================================================================
# 8. ORDER ALIGNMENT: REFERENCE → TRAIN / TEST
# ============================================================================

log_section(5, "ALIGNING REFERENCE ROWS TO AUTHORITATIVE TRAIN/TEST ORDER")

train_order = train["np_id"].astype(str).tolist()
test_order = test["np_id"].astype(str).tolist()

ref_index = pd.Series(
    np.arange(len(reference)),
    index=reference["np_id"].astype(str),
)

train_ref_indices = ref_index.loc[train_order].to_numpy(dtype=np.int64)
test_ref_indices = ref_index.loc[test_order].to_numpy(dtype=np.int64)

X_train = X_reference[train_ref_indices]
X_test = X_reference[test_ref_indices]

train_smiles = train["SMILES"].astype(str).tolist() if "SMILES" in train.columns else None
test_smiles = test["SMILES"].astype(str).tolist() if "SMILES" in test.columns else None

if train_smiles is not None and "SMILES" in reference.columns:
    ref_smiles_by_id = (
        reference.set_index("np_id")["SMILES"].astype(str)
    )
    ref_train_smiles = ref_smiles_by_id.loc[train_order].tolist()
    ref_test_smiles = ref_smiles_by_id.loc[test_order].tolist()

    train_smiles_match = all(a == b for a, b in zip(train_smiles, ref_train_smiles))
    test_smiles_match = all(a == b for a, b in zip(test_smiles, ref_test_smiles))

    if not train_smiles_match or not test_smiles_match:
        raise RuntimeError(
            "SMILES alignment between authoritative split and Script-04 "
            "reference failed."
        )

    print("TRAIN SMILES alignment : PASS")
    print("TEST SMILES alignment  : PASS")
else:
    train_smiles_match = None
    test_smiles_match = None
    print("SMILES alignment : NOT TESTED because SMILES column was unavailable.")


if not np.array_equal(
    reference.loc[train_ref_indices, "np_id"].astype(str).to_numpy(),
    np.array(train_order, dtype=str),
):
    raise RuntimeError("TRAIN np_id row alignment failed.")

if not np.array_equal(
    reference.loc[test_ref_indices, "np_id"].astype(str).to_numpy(),
    np.array(test_order, dtype=str),
):
    raise RuntimeError("TEST np_id row alignment failed.")

print(f"TRAIN aligned 40D matrix : {X_train.shape}")
print(f"TEST aligned 40D matrix  : {X_test.shape}")


# ============================================================================
# 9. TRAIN-ONLY STANDARDIZATION
# ============================================================================

log_section(6, "FITTING TRAIN-ONLY 40D STANDARDIZATION")

train_mean = np.mean(X_train, axis=0, dtype=np.float64)
train_std = np.std(X_train, axis=0, ddof=0, dtype=np.float64)

if not np.isfinite(train_mean).all() or not np.isfinite(train_std).all():
    raise RuntimeError("Non-finite train mean/std encountered.")

zero_std = np.where(train_std <= 0.0)[0]

if len(zero_std) > 0:
    names = [feature_cols[i] for i in zero_std]
    raise RuntimeError(
        "Zero-variance feature(s) detected in TRAIN 40D representation:\n"
        + "\n".join(names)
    )

X_train_std = (X_train - train_mean) / train_std
X_test_std = (X_test - train_mean) / train_std
X_reference_std = (X_reference - train_mean) / train_std

for label, arr in [
    ("TRAIN standardized", X_train_std),
    ("TEST standardized", X_test_std),
    ("REFERENCE standardized", X_reference_std),
]:
    n_nan, n_inf, n_nonfinite = finite_array_qc(arr)
    print(f"{label}: NaN={n_nan} Inf={n_inf}")
    if n_nonfinite:
        raise RuntimeError(f"{label} contains non-finite values.")

standardization_parameters = pd.DataFrame(
    {
        "feature_order": np.arange(1, EXPECTED_FEATURE_COUNT + 1),
        "feature_name": feature_cols,
        "feature_family": (
            ["Molecular"] * 10
            + ["3D-QSAR"] * 9
            + ["MoLFormer"] * 21
        ),
        "train_mean": train_mean,
        "train_std_ddof0": train_std,
        "train_min": X_train.min(axis=0),
        "train_max": X_train.max(axis=0),
    }
)

write_tsv(
    standardization_parameters,
    OUTPUT_FILES["standardization_parameters"],
)

standardization_qc_rows = []

for split_name, arr in [
    ("TRAIN", X_train_std),
    ("TEST", X_test_std),
    ("REFERENCE", X_reference_std),
]:
    standardization_qc_rows.append(
        {
            "dataset": split_name,
            "rows": int(arr.shape[0]),
            "features": int(arr.shape[1]),
            "nan_count": int(np.isnan(arr).sum()),
            "inf_count": int(np.isinf(arr).sum()),
            "min": float(np.min(arr)),
            "max": float(np.max(arr)),
            "mean": float(np.mean(arr)),
            "std": float(np.std(arr, ddof=0)),
            "status": status(
                np.isfinite(arr).all()
                and arr.shape[1] == EXPECTED_FEATURE_COUNT
            ),
        }
    )

write_tsv(
    pd.DataFrame(standardization_qc_rows),
    OUTPUT_FILES["standardization_qc"],
)


# ============================================================================
# 10. ROW-NORMALIZE FOR COSINE SIMILARITY
# ============================================================================

log_section(7, "CONSTRUCTING STANDARDIZED COSINE SIMILARITY REPRESENTATION")

reference_norms = np.linalg.norm(X_reference_std, axis=1)

if not np.isfinite(reference_norms).all():
    raise RuntimeError("Non-finite row norm found in standardized reference.")

zero_norm_rows = np.where(reference_norms <= 0.0)[0]

if len(zero_norm_rows):
    raise RuntimeError(
        f"{len(zero_norm_rows)} standardized reference rows have zero norm."
    )

X_reference_cosine = X_reference_std / reference_norms[:, None]

train_norms = np.linalg.norm(X_train_std, axis=1)
test_norms = np.linalg.norm(X_test_std, axis=1)

if np.any(train_norms <= 0.0) or np.any(test_norms <= 0.0):
    raise RuntimeError("Zero-norm TRAIN or TEST vector detected.")

X_train_cosine = X_train_std / train_norms[:, None]
X_test_cosine = X_test_std / test_norms[:, None]

norm_min, norm_max, norm_mean = cosine_similarity_self_check(
    X_reference_cosine
)

print(f"Reference normalized row norm min : {norm_min:.12f}")
print(f"Reference normalized row norm max : {norm_max:.12f}")
print(f"Reference normalized row norm mean: {norm_mean:.12f}")

if not (
    math.isclose(norm_min, 1.0, rel_tol=1e-9, abs_tol=1e-9)
    and math.isclose(norm_max, 1.0, rel_tol=1e-9, abs_tol=1e-9)
):
    raise RuntimeError("Cosine normalization QC failed.")


# ============================================================================
# 11. WRITE STANDARDIZED MATRICES
# ============================================================================

log_section(8, "WRITING STANDARDIZED 40D MATRICES")

standardized_reference_df = pd.DataFrame(
    X_reference_std,
    columns=feature_cols,
)

standardized_reference_df.insert(
    0,
    "np_id",
    reference["np_id"].astype(str).to_numpy(),
)

standardized_reference_df.insert(
    1,
    "split",
    reference["split"].astype(str).to_numpy(),
)

write_tsv(
    standardized_reference_df,
    OUTPUT_FILES["standardized_matrix"],
)

write_tsv(
    standardized_reference_df,
    OUTPUT_FILES["standardized_id_matrix"],
)

train_standardized_df = pd.DataFrame(
    X_train_std,
    columns=feature_cols,
)
train_standardized_df.insert(0, "np_id", train_order)

test_standardized_df = pd.DataFrame(
    X_test_std,
    columns=feature_cols,
)
test_standardized_df.insert(0, "np_id", test_order)

write_tsv(
    train_standardized_df,
    OUTPUT_FILES["train_standardized_matrix"],
)

write_tsv(
    test_standardized_df,
    OUTPUT_FILES["test_standardized_matrix"],
)

print(
    f"Standardized reference : "
    f"{OUTPUT_FILES['standardized_matrix']}"
)
print(f"TRAIN standardized : {X_train_std.shape}")
print(f"TEST standardized  : {X_test_std.shape}")


# ============================================================================
# 12. BUILD COSINE NEAREST-NEIGHBOR INDEX
# ============================================================================

log_section(9, "BUILDING 40D COSINE NEAREST-NEIGHBOR INDEX")

neighbor_count = min(NEIGHBOR_COUNT, len(reference))

nn = NearestNeighbors(
    n_neighbors=neighbor_count,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1,
)

nn.fit(X_reference_std)

# Self-check on a small deterministic sample.
sample_n = min(100, len(reference))
sample_idx = np.arange(sample_n, dtype=np.int64)

sample_dist, sample_ind = nn.kneighbors(
    X_reference_std[sample_idx],
    n_neighbors=min(5, neighbor_count),
    return_distance=True,
)

sample_self_ok = True

for row_i in range(sample_n):
    if sample_ind[row_i, 0] != sample_idx[row_i]:
        sample_self_ok = False
        break

if not sample_self_ok:
    raise RuntimeError(
        "Cosine nearest-neighbor self-retrieval failed."
    )

sample_self_similarity = 1.0 - sample_dist[:, 0]

print(f"Index metric : cosine distance")
print(f"Index rows   : {len(reference):,}")
print(f"Neighbors    : {neighbor_count}")
print(f"Self-retrieval : PASS")
print(
    f"Self similarity range : "
    f"{sample_self_similarity.min():.12f}–"
    f"{sample_self_similarity.max():.12f}"
)

joblib.dump(
    {
        "index": nn,
        "metric": "cosine",
        "feature_space": "40D standardized Model-1 representation",
        "feature_order": feature_cols,
        "reference_rows": EXPECTED_REFERENCE_ROWS,
        "neighbor_count": neighbor_count,
        "standardization_parameters": standardization_parameters,
        "fit_dataset": "CMAUP Script-04 60,190-molecule reference",
        "training_only_standardization": True,
        "random_state": RANDOM_STATE,
    },
    OUTPUT_FILES["cosine_neighbor_index"],
    compress=3,
)

# Store deterministic TRAIN query examples against the complete reference.
train_query_n = min(100, len(train_order))
train_query_idx = np.arange(train_query_n, dtype=np.int64)

train_dist, train_ind = nn.kneighbors(
    X_train_std[train_query_idx],
    n_neighbors=neighbor_count,
    return_distance=True,
)

neighbor_rows = []

for qpos in range(train_query_n):
    query_id = train_order[qpos]

    for rank in range(neighbor_count):
        ridx = int(train_ind[qpos, rank])
        distance = float(train_dist[qpos, rank])
        similarity = float(1.0 - distance)

        neighbor_rows.append(
            {
                "query_np_id": query_id,
                "query_split": "TRAIN",
                "rank": rank + 1,
                "reference_np_id": str(reference.iloc[ridx]["np_id"]),
                "reference_split": str(reference.iloc[ridx]["split"]),
                "cosine_distance": distance,
                "cosine_similarity": similarity,
            }
        )

write_tsv(
    pd.DataFrame(neighbor_rows),
    OUTPUT_FILES["cosine_neighbor_ids"],
)

write_tsv(
    pd.DataFrame(
        [
            {
                "check": "neighbor_index_self_retrieval_sample",
                "sample_rows": sample_n,
                "status": "PASS" if sample_self_ok else "FAIL",
            },
            {
                "check": "neighbor_index_metric",
                "sample_rows": len(reference),
                "status": "PASS" if nn.metric == "cosine" else "FAIL",
            },
            {
                "check": "neighbor_index_reference_rows",
                "sample_rows": len(reference),
                "status": status(
                    len(reference) == EXPECTED_REFERENCE_ROWS
                ),
            },
        ]
    ),
    OUTPUT_FILES["neighbor_qc"],
)


# ============================================================================
# 13. BUILD INDEPENDENT MORGAN / ECFP4 COMPARATOR
# ============================================================================

log_section(10, "BUILDING INDEPENDENT MORGAN / ECFP4 COMPARATOR")

if "SMILES" not in reference.columns:
    raise RuntimeError(
        "Script-04 reference lacks SMILES; cannot build Morgan comparator."
    )

smiles_values = reference["SMILES"].astype(str).tolist()

packed_rows = []
morgan_qc_rows = []

valid_count = 0
invalid_count = 0

for start in range(0, len(smiles_values), MORGAN_CHUNK_SIZE):
    stop = min(start + MORGAN_CHUNK_SIZE, len(smiles_values))

    for idx in range(start, stop):
        smi = smiles_values[idx]

        fp = make_morgan_fp(smi)

        if fp is None:
            invalid_count += 1
            morgan_qc_rows.append(
                {
                    "np_id": str(reference.iloc[idx]["np_id"]),
                    "smiles_valid_for_morgan": False,
                    "fingerprint_generated": False,
                    "bit_count": np.nan,
                    "status": "FAIL",
                }
            )
            packed_rows.append(
                np.zeros(MORGAN_NBITS // 8, dtype=np.uint8)
            )
            continue

        packed = bitvect_to_packed(fp)
        packed_rows.append(packed)
        valid_count += 1

        morgan_qc_rows.append(
            {
                "np_id": str(reference.iloc[idx]["np_id"]),
                "smiles_valid_for_morgan": True,
                "fingerprint_generated": True,
                "bit_count": int(fp.GetNumOnBits()),
                "status": "PASS",
            }
        )

    print(
        f"Morgan progress: {stop:,}/{len(smiles_values):,}",
        flush=True,
    )

morgan_packed = np.vstack(packed_rows).astype(np.uint8)

expected_bytes_per_fp = MORGAN_NBITS // 8

if morgan_packed.shape != (
    EXPECTED_REFERENCE_ROWS,
    expected_bytes_per_fp,
):
    raise RuntimeError(
        f"Morgan packed matrix shape mismatch: {morgan_packed.shape}; "
        f"expected {(EXPECTED_REFERENCE_ROWS, expected_bytes_per_fp)}"
    )

np.savez_compressed(
    OUTPUT_FILES["morgan_fingerprints"],
    np_id=reference["np_id"].astype(str).to_numpy(),
    packed_bits=morgan_packed,
    radius=np.array([MORGAN_RADIUS], dtype=np.int32),
    n_bits=np.array([MORGAN_NBITS], dtype=np.int32),
    fingerprint_type=np.array(["Morgan/ECFP4"]),
)

write_tsv(
    pd.DataFrame(morgan_qc_rows),
    OUTPUT_FILES["morgan_qc"],
)

morgan_bit_counts = packed_to_bit_count(morgan_packed)

write_tsv(
    pd.DataFrame(
        {
            "np_id": reference["np_id"].astype(str),
            "split": reference["split"].astype(str),
            "morgan_ecfp4_bit_count": morgan_bit_counts,
        }
    ),
    OUTPUT_FILES["morgan_metadata"],
)

print(f"Morgan radius : {MORGAN_RADIUS}")
print(f"Morgan bits   : {MORGAN_NBITS}")
print(f"Valid fingerprints : {valid_count:,}")
print(f"Invalid fingerprints: {invalid_count:,}")

# Since Script 04 already established valid SMILES and all reference rows
# originate from the Model-1 union, an invalid Morgan fingerprint here is a
# genuine integrity failure rather than a value to silently impute.
if invalid_count != 0:
    raise RuntimeError(
        f"Morgan fingerprint generation failed for {invalid_count} reference molecules."
    )

if not np.all(morgan_bit_counts > 0):
    raise RuntimeError(
        "One or more valid molecules produced a zero-bit Morgan fingerprint."
    )


# ============================================================================
# 14. MORGAN DETERMINISTIC SELF-SIMILARITY CHECK
# ============================================================================

log_section(11, "MORGAN / ECFP4 SELF-SIMILARITY QC")

# Deterministic exact self-similarity checks on the first 100 fingerprints.
morgan_self_qc = []

for idx in range(min(100, EXPECTED_REFERENCE_ROWS)):
    fp = make_morgan_fp(smiles_values[idx])
    if fp is None:
        raise RuntimeError(
            f"Unexpected invalid Morgan fingerprint during self-QC: "
            f"{reference.iloc[idx]['np_id']}"
        )

    sim = DataStructs.TanimotoSimilarity(fp, fp)

    morgan_self_qc.append(float(sim))

morgan_self_min = min(morgan_self_qc)
morgan_self_max = max(morgan_self_qc)

print(
    f"Morgan self Tanimoto range : "
    f"{morgan_self_min:.12f}–{morgan_self_max:.12f}"
)

if not (
    math.isclose(morgan_self_min, 1.0, abs_tol=1e-12)
    and math.isclose(morgan_self_max, 1.0, abs_tol=1e-12)
):
    raise RuntimeError("Morgan self-similarity QC failed.")


# ============================================================================
# 15. SIMILARITY QC
# ============================================================================

log_section(12, "SIMILARITY QC")

similarity_qc = [
    {
        "representation": "Model-1 exact 40D",
        "feature_count": 40,
        "preprocessing": "Script-04 exact post-Model-1 representation",
        "scaling": "TRAIN-ONLY z-standardization",
        "similarity": "cosine similarity",
        "target_data_used": False,
        "activity_labels_used": False,
        "status": "PASS",
    },
    {
        "representation": "Morgan/ECFP4 comparator",
        "feature_count": MORGAN_NBITS,
        "preprocessing": "RDKit Morgan radius=2",
        "scaling": "not applicable",
        "similarity": "Tanimoto similarity",
        "target_data_used": False,
        "activity_labels_used": False,
        "status": "PASS",
    },
]

write_tsv(
    pd.DataFrame(similarity_qc),
    OUTPUT_FILES["similarity_qc"],
)


# ============================================================================
# 16. WRITE FINAL QC / MANIFEST
# ============================================================================

log_section(13, "WRITING FINAL QC AND MANIFEST")

run_end = datetime.now().astimezone()
duration_seconds = (run_end - RUN_START).total_seconds()

all_output_hashes = {}

for label, path in OUTPUT_FILES.items():
    if path.exists() and path.is_file():
        all_output_hashes[label] = {
            "path": str(path.relative_to(PULP_DIR)),
            "size_bytes": int(path.stat().st_size),
            "sha256": sha256_file(path),
        }

qc_checks = [
    {
        "check": "script04_reference_rows",
        "expected": EXPECTED_REFERENCE_ROWS,
        "observed": len(reference),
        "status": status(len(reference) == EXPECTED_REFERENCE_ROWS),
    },
    {
        "check": "script04_feature_count",
        "expected": EXPECTED_FEATURE_COUNT,
        "observed": len(feature_cols),
        "status": status(len(feature_cols) == EXPECTED_FEATURE_COUNT),
    },
    {
        "check": "train_rows",
        "expected": EXPECTED_TRAIN_ROWS,
        "observed": len(train),
        "status": status(len(train) == EXPECTED_TRAIN_ROWS),
    },
    {
        "check": "test_rows",
        "expected": EXPECTED_TEST_ROWS,
        "observed": len(test),
        "status": status(len(test) == EXPECTED_TEST_ROWS),
    },
    {
        "check": "train_test_overlap",
        "expected": 0,
        "observed": len(overlap),
        "status": status(len(overlap) == 0),
    },
    {
        "check": "final_40d_nonfinite",
        "expected": 0,
        "observed": int(np.isnan(X_reference).sum() + np.isinf(X_reference).sum()),
        "status": status(np.isfinite(X_reference).all()),
    },
    {
        "check": "standardized_40d_nonfinite",
        "expected": 0,
        "observed": int(
            np.isnan(X_reference_std).sum()
            + np.isinf(X_reference_std).sum()
        ),
        "status": status(np.isfinite(X_reference_std).all()),
    },
    {
        "check": "zero_variance_features",
        "expected": 0,
        "observed": len(zero_std),
        "status": status(len(zero_std) == 0),
    },
    {
        "check": "cosine_zero_norm_rows",
        "expected": 0,
        "observed": len(zero_norm_rows),
        "status": status(len(zero_norm_rows) == 0),
    },
    {
        "check": "morgan_invalid_fingerprints",
        "expected": 0,
        "observed": invalid_count,
        "status": status(invalid_count == 0),
    },
    {
        "check": "morgan_self_similarity_min",
        "expected": 1.0,
        "observed": morgan_self_min,
        "status": status(math.isclose(morgan_self_min, 1.0, abs_tol=1e-12)),
    },
    {
        "check": "morgan_self_similarity_max",
        "expected": 1.0,
        "observed": morgan_self_max,
        "status": status(math.isclose(morgan_self_max, 1.0, abs_tol=1e-12)),
    },
    {
        "check": "neighbor_self_retrieval_sample",
        "expected": "PASS",
        "observed": "PASS" if sample_self_ok else "FAIL",
        "status": "PASS" if sample_self_ok else "FAIL",
    },
]

qc_df = pd.DataFrame(qc_checks)
write_tsv(qc_df, OUTPUT_FILES["similarity_qc"])

final_status = "PASS" if (qc_df["status"] == "FAIL").sum() == 0 else "FAIL"

manifest = {
    "script": "05_build_cmaup_40d_similarity_index.py",
    "version": "exact_model1_40d_train_only_standardized_cosine_plus_morgan_comparator",
    "start_time": RUN_START.isoformat(),
    "finish_time": run_end.isoformat(),
    "duration_seconds": duration_seconds,
    "final_status": final_status,
    "pulP_directory": str(PULP_DIR),
    "input_reference": str(REFERENCE_FILE.relative_to(PULP_DIR)),
    "input_reference_sha256": sha256_file(REFERENCE_FILE),
    "reference_rows": EXPECTED_REFERENCE_ROWS,
    "train_rows": EXPECTED_TRAIN_ROWS,
    "test_rows": EXPECTED_TEST_ROWS,
    "feature_count": EXPECTED_FEATURE_COUNT,
    "feature_space_dimension": EXPECTED_FEATURE_COUNT,
    "feature_order": feature_cols,
    "feature_families": {
        "Molecular": EXPECTED_MOLECULAR_FEATURES,
        "3D-QSAR": EXPECTED_3D_FEATURES,
        "MoLFormer": EXPECTED_MOLFORMER_FEATURES,
    },
    "standardization": {
        "method": "z-score",
        "fit_on": "TRAIN ONLY",
        "ddof": 0,
        "new_imputation": False,
        "new_features_generated": False,
        "target_data_used": False,
        "activity_labels_used": False,
        "parameters_file": str(
            OUTPUT_FILES["standardization_parameters"].relative_to(PULP_DIR)
        ),
    },
    "primary_similarity": {
        "representation": "exact Model-1 40D representation",
        "standardized": True,
        "row_normalized": True,
        "metric": "cosine similarity",
        "index_algorithm": "brute-force exact cosine",
        "neighbor_count": NEIGHBOR_COUNT,
        "index_file": str(
            OUTPUT_FILES["cosine_neighbor_index"].relative_to(PULP_DIR)
        ),
    },
    "independent_2d_comparator": {
        "representation": "Morgan/ECFP4",
        "radius": MORGAN_RADIUS,
        "n_bits": MORGAN_NBITS,
        "metric": "Tanimoto similarity",
        "fingerprints_file": str(
            OUTPUT_FILES["morgan_fingerprints"].relative_to(PULP_DIR)
        ),
    },
    "model_training_performed": False,
    "target_inference_performed": False,
    "output_hashes": all_output_hashes,
    "qc_checks": qc_checks,
}

with OUTPUT_FILES["run_manifest"].open("w") as fh:
    json.dump(manifest, fh, indent=2, sort_keys=True)

qc_lines = [
    "=" * 78,
    "SCRIPT 05 — CMAUP 40D SIMILARITY REFERENCE / INDEX QC",
    "=" * 78,
    f"Start time : {RUN_START.isoformat()}",
    f"Finish time: {run_end.isoformat()}",
    f"Duration   : {duration_seconds:.3f} seconds",
    "",
    f"Reference rows : {EXPECTED_REFERENCE_ROWS:,}",
    f"TRAIN rows    : {EXPECTED_TRAIN_ROWS:,}",
    f"TEST rows     : {EXPECTED_TEST_ROWS:,}",
    f"Feature count : {EXPECTED_FEATURE_COUNT}",
    "",
    "Primary representation:",
    "  Exact Script-04 40D Model-1 feature space",
    "  TRAIN-ONLY z-standardization",
    "  Cosine similarity",
    "",
    "Independent comparator:",
    f"  Morgan/ECFP4 radius={MORGAN_RADIUS}, {MORGAN_NBITS} bits",
    "  Tanimoto similarity",
    "",
    f"40D non-finite values : {int(np.isnan(X_reference).sum() + np.isinf(X_reference).sum())}",
    f"Standardized non-finite values : {int(np.isnan(X_reference_std).sum() + np.isinf(X_reference_std).sum())}",
    f"Zero-variance features : {len(zero_std)}",
    f"Zero-norm rows : {len(zero_norm_rows)}",
    f"Morgan invalid fingerprints : {invalid_count}",
    f"Morgan self similarity min : {morgan_self_min:.12f}",
    f"Morgan self similarity max : {morgan_self_max:.12f}",
    f"Cosine self-retrieval sample : {'PASS' if sample_self_ok else 'FAIL'}",
    "",
    "Important:",
    "  No target annotations were used.",
    "  No activity labels were used.",
    "  No target model was trained.",
    "  No new imputation was performed.",
    "  No new 40D descriptors or embeddings were generated.",
    "",
    f"FINAL STATUS : {final_status}",
]

OUTPUT_FILES["qc_text"].write_text("\n".join(qc_lines) + "\n")

# Refresh output hashes after all files have been finalized.
final_output_hashes = {}

for label, path in OUTPUT_FILES.items():
    if path.exists() and path.is_file():
        final_output_hashes[label] = {
            "path": str(path.relative_to(PULP_DIR)),
            "size_bytes": int(path.stat().st_size),
            "sha256": sha256_file(path),
        }

manifest["output_hashes"] = final_output_hashes

with OUTPUT_FILES["run_manifest"].open("w") as fh:
    json.dump(manifest, fh, indent=2, sort_keys=True)


# ============================================================================
# 17. OUTPUT INVENTORY
# ============================================================================

log_section(14, "OUTPUT INVENTORY")

for label, path in OUTPUT_FILES.items():
    if path.exists():
        print(f"{path.name:<55} {path.stat().st_size:,} bytes")
    else:
        print(f"{path.name:<55} NOT FOUND")


# ============================================================================
# 18. FINAL STATUS
# ============================================================================

print("\n" + "=" * 78)
print("FINAL STATUS")
print("=" * 78)
print(f"{final_status}")
print(f"CMAUP reference records : {EXPECTED_REFERENCE_ROWS:,}")
print(f"TRAIN records           : {EXPECTED_TRAIN_ROWS:,}")
print(f"TEST records            : {EXPECTED_TEST_ROWS:,}")
print(f"Final features          : {EXPECTED_FEATURE_COUNT}")
print("Primary similarity      : standardized 40D cosine")
print("Comparator              : Morgan/ECFP4 Tanimoto")
print("Target information used : NO")
print("Model training          : NO")
print("Target inference        : NO")
print()
print(
    "Primary index:",
    OUTPUT_FILES["cosine_neighbor_index"],
)
print(
    "Standardization parameters:",
    OUTPUT_FILES["standardization_parameters"],
)
print(
    "Morgan fingerprints:",
    OUTPUT_FILES["morgan_fingerprints"],
)
print(
    "Manifest:",
    OUTPUT_FILES["run_manifest"],
)
print(
    "QC:",
    OUTPUT_FILES["qc_text"],
)

print("\n" + "=" * 42)
print("FINISHED")
print(f"End time: {run_end.strftime('%a %b %d %H:%M:%S %Z %Y')}")
print("=" * 42)

if final_status != "PASS":
    raise RuntimeError(
        "SCRIPT 05 FAILED. Review 05_cmaup_40d_similarity_qc.txt and "
        "similarity_qc.tsv before proceeding."
    )
