#!/usr/bin/env python3

"""
======================================================================
SCRIPT 05 v3
RDKit 217 + 3D 11 FEATURE INTEGRATION
======================================================================

Purpose
-------
Merge:
    217 RDKit molecular descriptors
    +
    11 3D structure-derived descriptors

Total initial ML features:
    228

The script performs:

1. Load RDKit descriptor datasets
2. Load 3D QSAR descriptor datasets
3. Validate row counts
4. Validate np_id uniqueness
5. Validate train/test separation
6. Validate RDKit <-> 3D ID matching
7. Select RDKit descriptors ONLY from descriptor_list.txt
8. Select the 11 actual 3D descriptors
9. Merge RDKit + 3D features
10. Perform QC using TRAINING data only
11. Remove features with excessive missingness
12. Median-impute retained features using TRAINING medians
13. Apply training medians to TEST
14. Remove zero/near-zero variance features based on TRAIN
15. Remove highly correlated features based on TRAIN
16. Apply exactly the same feature selection to TEST
17. Check NaN / Inf
18. Check duplicate feature columns
19. Save final train/test feature-ready datasets
20. Save feature list
21. Save removed-feature list
22. Save preprocessing statistics
23. Save QC summary

Important
---------
No test-set information is used to determine feature filtering.

No scaling is performed here.
Training scaling statistics are saved for later ML pipelines.

Target:
    Activity_Label

Initial features:
    217 RDKit + 11 3D = 228
======================================================================
"""

import os
import sys
import time
import warnings

import numpy as np
import pandas as pd

from rdkit import Chem
from rdkit import RDLogger

warnings.filterwarnings("ignore")
RDLogger.DisableLog("rdApp.*")


# ======================================================================
# CONFIGURATION
# ======================================================================

RDKit_TRAIN = (
    "feature_engineering/molecular_descriptors/"
    "train_80_molecular_descriptors.tsv"
)

RDKit_TEST = (
    "feature_engineering/molecular_descriptors/"
    "test_20_molecular_descriptors.tsv"
)

THREE_D_TRAIN = (
    "feature_engineering/3d_qsar_descriptors/"
    "train_80_3d_qsar_descriptors.tsv"
)

THREE_D_TEST = (
    "feature_engineering/3d_qsar_descriptors/"
    "test_20_3d_qsar_descriptors.tsv"
)

DESCRIPTOR_LIST = (
    "feature_engineering/molecular_descriptors/"
    "descriptor_list.txt"
)

OUTPUT_DIR = "feature_engineering/final_228_features"

TRAIN_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "train_80_final_228_features.tsv"
)

TEST_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "test_20_final_228_features.tsv"
)

FEATURE_LIST_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "feature_list.txt"
)

REMOVED_FEATURE_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "removed_features.txt"
)

PREPROCESSING_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "preprocessing_statistics.tsv"
)

QC_SUMMARY_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "qc_summary.txt"
)

REMOVAL_LOG_OUTPUT = os.path.join(
    OUTPUT_DIR,
    "feature_removal_log.tsv"
)


# ======================================================================
# EXPECTED FEATURES
# ======================================================================

EXPECTED_RDKIT = 217
EXPECTED_3D = 11
EXPECTED_TOTAL = 228

# The 11 actual 3D descriptors generated by Script 04 v2
THREE_D_FEATURES = [
    "PMI1",
    "PMI2",
    "PMI3",
    "NPR1",
    "NPR2",
    "RadiusOfGyration",
    "InertialShapeFactor",
    "Eccentricity",
    "Asphericity",
    "SpherocityIndex",
    "PBF",
]

TARGET_COLUMN = "Activity_Label"
ID_COLUMN = "np_id"

# Missingness threshold determined only from TRAINING data.
# 0.20 means remove a feature if >20% of training molecules
# have missing values.
MISSINGNESS_THRESHOLD = 0.20

# Near-zero variance threshold.
VARIANCE_THRESHOLD = 1e-12

# Correlation threshold.
CORRELATION_THRESHOLD = 0.95


# ======================================================================
# NON-FEATURE COLUMNS
# ======================================================================

NON_FEATURE_COLUMNS = {
    "np_id",
    "pref_name",
    "iupac_name",
    "SMILES",
    "Canonical_SMILES",

    "Activity_Status",
    "Activity_Label",

    "chembl_id",
    "pubchem_cid",

    "MW",
    "LogS",
    "LogD",
    "LogP",
    "nHA",
    "nHD",
    "TPSA",
    "nRot",
    "nRing",

    "InChI",
    "InChIKey",

    # 3D QC / generation metadata
    "3D_Status",
    "Optimization_Method",
    "Best_Conformer_Energy",
    "Conformers_Generated",
    "Metal_Containing",
}


# ======================================================================
# UTILITY FUNCTIONS
# ======================================================================

def print_header(text):
    print()
    print("=" * 78)
    print(text)
    print("=" * 78)


def fail(message):
    print()
    print("ERROR:")
    print(message)
    sys.exit(1)


def check_file(path):
    if not os.path.isfile(path):
        fail(f"Required file not found:\n{path}")


def load_tsv(path):
    print(f"Loading:\n{path}")
    try:
        df = pd.read_csv(
            path,
            sep="\t",
            low_memory=False
        )
    except Exception as e:
        fail(f"Could not read {path}\n{e}")

    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns):,}")

    return df


def check_unique_ids(df, name):
    if ID_COLUMN not in df.columns:
        fail(f"{name}: missing {ID_COLUMN} column")

    duplicated = df[ID_COLUMN].duplicated().sum()

    print(f"{name} duplicate {ID_COLUMN}: {duplicated}")

    if duplicated > 0:
        fail(f"{name} contains duplicate {ID_COLUMN} values.")

    return duplicated


def check_row_count(df, expected, name):
    if len(df) != expected:
        fail(
            f"{name} row count mismatch.\n"
            f"Expected: {expected:,}\n"
            f"Found:    {len(df):,}"
        )

    print(f"{name}: PASS ({len(df):,})")


def check_train_test_overlap(train, test):
    overlap = set(train[ID_COLUMN]) & set(test[ID_COLUMN])

    print(f"Train/test overlapping IDs: {len(overlap)}")

    if overlap:
        fail(
            "TRAIN/TEST LEAKAGE DETECTED.\n"
            f"Overlapping IDs: {list(overlap)[:10]}"
        )

    print("Train/test separation: PASS")


def read_descriptor_list(path):

    with open(path, "r") as f:
        descriptors = [
            line.strip()
            for line in f
            if line.strip()
        ]

    return descriptors


# ======================================================================
# FEATURE VALIDATION
# ======================================================================

def validate_rdkit_descriptors(train, test, descriptor_list):

    print()
    print("RDKit descriptor validation")

    print(f"Descriptor list entries: {len(descriptor_list)}")

    if len(descriptor_list) != EXPECTED_RDKIT:
        fail(
            f"descriptor_list.txt contains {len(descriptor_list)} "
            f"descriptors, expected {EXPECTED_RDKIT}."
        )

    missing_train = [
        x for x in descriptor_list
        if x not in train.columns
    ]

    missing_test = [
        x for x in descriptor_list
        if x not in test.columns
    ]

    if missing_train:
        fail(
            "RDKit TRAIN missing descriptors:\n"
            + "\n".join(missing_train)
        )

    if missing_test:
        fail(
            "RDKit TEST missing descriptors:\n"
            + "\n".join(missing_test)
        )

    print("RDKit TRAIN descriptor validation: PASS")
    print("RDKit TEST descriptor validation : PASS")

    return descriptor_list


def validate_3d_descriptors(train, test):

    print()
    print("3D descriptor validation")

    missing_train = [
        x for x in THREE_D_FEATURES
        if x not in train.columns
    ]

    missing_test = [
        x for x in THREE_D_FEATURES
        if x not in test.columns
    ]

    if missing_train:
        fail(
            "3D TRAIN missing descriptors:\n"
            + "\n".join(missing_train)
        )

    if missing_test:
        fail(
            "3D TEST missing descriptors:\n"
            + "\n".join(missing_test)
        )

    print(f"3D descriptors: {len(THREE_D_FEATURES)}")
    print("3D TRAIN descriptor validation: PASS")
    print("3D TEST descriptor validation : PASS")

    return THREE_D_FEATURES


# ======================================================================
# ID MATCHING
# ======================================================================

def check_id_matching(rdkit_train, three_d_train,
                      rdkit_test, three_d_test):

    print_header("RDKit <-> 3D ID MATCHING")

    rtrain = set(rdkit_train[ID_COLUMN])
    ttrain = set(three_d_train[ID_COLUMN])

    rtest = set(rdkit_test[ID_COLUMN])
    ttest = set(three_d_test[ID_COLUMN])

    missing_rtrain = rtrain - ttrain
    missing_ttrain = ttrain - rtrain

    missing_rtest = rtest - ttest
    missing_ttest = ttest - rtest

    print(
        f"Training RDKit IDs missing from 3D: "
        f"{len(missing_rtrain)}"
    )

    print(
        f"Training 3D IDs missing from RDKit: "
        f"{len(missing_ttrain)}"
    )

    print(
        f"Testing RDKit IDs missing from 3D: "
        f"{len(missing_rtest)}"
    )

    print(
        f"Testing 3D IDs missing from RDKit: "
        f"{len(missing_ttest)}"
    )

    if (
        missing_rtrain
        or missing_ttrain
        or missing_rtest
        or missing_ttest
    ):
        fail("RDKit/3D ID matching failed.")

    print("RDKit <-> 3D ID matching: PASS")


# ======================================================================
# MERGE
# ======================================================================

def merge_features(rdkit_df, three_d_df, rdkit_features):

    columns_3d = [ID_COLUMN] + THREE_D_FEATURES

    rdkit_part = rdkit_df[
        [ID_COLUMN] + rdkit_features
    ].copy()

    three_d_part = three_d_df[
        columns_3d
    ].copy()

    merged = pd.merge(
        rdkit_part,
        three_d_part,
        on=ID_COLUMN,
        how="inner",
        validate="one_to_one"
    )

    if len(merged) != len(rdkit_df):
        fail(
            "Merge changed row count.\n"
            f"Original: {len(rdkit_df):,}\n"
            f"Merged:   {len(merged):,}"
        )

    return merged


# ======================================================================
# NUMERIC CONVERSION
# ======================================================================

def force_numeric(df, features, dataset_name):

    conversion_failures = []

    for feature in features:

        original = df[feature]

        converted = pd.to_numeric(
            original,
            errors="coerce"
        )

        newly_missing = (
            original.notna()
            & converted.isna()
        ).sum()

        if newly_missing > 0:
            conversion_failures.append(
                (feature, int(newly_missing))
            )

        df[feature] = converted

    if conversion_failures:

        print(
            f"\n{dataset_name}: non-numeric values converted "
            "to NaN:"
        )

        for feature, count in conversion_failures:
            print(
                f"  {feature}: {count}"
            )

    return df


# ======================================================================
# TRAIN-ONLY MISSINGNESS QC
# ======================================================================

def missingness_qc(train, test, features):

    print_header("TRAIN-ONLY MISSINGNESS QC")

    missing_train = train[features].isna().sum()
    missing_test = test[features].isna().sum()

    train_missing_fraction = (
        missing_train / len(train)
    )

    remove = [
        feature
        for feature in features
        if train_missing_fraction[feature]
        > MISSINGNESS_THRESHOLD
    ]

    keep = [
        feature
        for feature in features
        if feature not in remove
    ]

    print(
        f"Missingness threshold: "
        f"{MISSINGNESS_THRESHOLD * 100:.1f}%"
    )

    print(
        f"Features removed by missingness: "
        f"{len(remove)}"
    )

    if remove:
        print("\nRemoved:")
        for feature in remove:
            print(
                f"  {feature}: "
                f"{train_missing_fraction[feature] * 100:.3f}%"
            )

    print(
        f"Features retained: {len(keep)}"
    )

    return keep, remove, missing_train, missing_test


# ======================================================================
# TRAIN-ONLY MEDIAN IMPUTATION
# ======================================================================

def median_imputation(train, test, features):

    print_header("TRAIN-ONLY MEDIAN IMPUTATION")

    train_medians = {}

    total_train_missing_before = (
        int(train[features].isna().sum().sum())
    )

    total_test_missing_before = (
        int(test[features].isna().sum().sum())
    )

    for feature in features:

        median = train[feature].median()

        if pd.isna(median):
            fail(
                f"Training median is NaN for feature: "
                f"{feature}"
            )

        train_medians[feature] = float(median)

        train[feature] = train[feature].fillna(median)
        test[feature] = test[feature].fillna(median)

    total_train_missing_after = (
        int(train[features].isna().sum().sum())
    )

    total_test_missing_after = (
        int(test[features].isna().sum().sum())
    )

    print(
        f"Training missing values before: "
        f"{total_train_missing_before:,}"
    )

    print(
        f"Testing missing values before : "
        f"{total_test_missing_before:,}"
    )

    print(
        f"Training missing values after : "
        f"{total_train_missing_after:,}"
    )

    print(
        f"Testing missing values after  : "
        f"{total_test_missing_after:,}"
    )

    if (
        total_train_missing_after > 0
        or total_test_missing_after > 0
    ):
        fail("Missing values remain after imputation.")

    return train_medians


# ======================================================================
# TRAIN-ONLY VARIANCE FILTER
# ======================================================================

def variance_filter(train, features):

    print_header("TRAIN-ONLY VARIANCE FILTER")

    variances = train[features].var(
        axis=0,
        ddof=0
    )

    remove = [
        feature
        for feature in features
        if (
            not np.isfinite(variances[feature])
            or variances[feature] <= VARIANCE_THRESHOLD
        )
    ]

    keep = [
        feature
        for feature in features
        if feature not in remove
    ]

    print(
        f"Variance threshold: {VARIANCE_THRESHOLD}"
    )

    print(
        f"Features removed: {len(remove)}"
    )

    if remove:
        print("\nRemoved:")
        for feature in remove:
            print(
                f"  {feature}: variance="
                f"{variances[feature]}"
            )

    print(
        f"Features retained: {len(keep)}"
    )

    return keep, remove, variances


# ======================================================================
# TRAIN-ONLY CORRELATION FILTER
# ======================================================================

def correlation_filter(train, features):

    print_header("TRAIN-ONLY CORRELATION FILTER")

    if len(features) <= 1:
        return features, [], {}

    print(
        f"Calculating correlation matrix for "
        f"{len(features)} features..."
    )

    corr = train[features].corr(
        method="pearson"
    )

    upper = corr.where(
        np.triu(
            np.ones(corr.shape),
            k=1
        ).astype(bool)
    )

    remove = set()
    correlation_pairs = []

    for column in upper.columns:

        correlated = upper.index[
            upper[column].abs()
            > CORRELATION_THRESHOLD
        ].tolist()

        for row in correlated:

            if row not in remove:

                remove.add(column)

                correlation_pairs.append(
                    (
                        row,
                        column,
                        float(corr.loc[row, column])
                    )
                )

                break

    remove = list(remove)

    keep = [
        feature
        for feature in features
        if feature not in remove
    ]

    print(
        f"Correlation threshold: "
        f"{CORRELATION_THRESHOLD}"
    )

    print(
        f"Features removed: {len(remove)}"
    )

    if correlation_pairs:

        print("\nHighly correlated pairs:")

        for a, b, r in correlation_pairs[:30]:

            print(
                f"  {a} <-> {b}: "
                f"r={r:.5f}"
            )

        if len(correlation_pairs) > 30:

            print(
                f"  ... and "
                f"{len(correlation_pairs) - 30} "
                f"additional pairs"
            )

    print(
        f"Features retained: {len(keep)}"
    )

    return keep, remove, correlation_pairs


# ======================================================================
# DUPLICATE FEATURE COLUMN CHECK
# ======================================================================

def duplicate_feature_columns(df, features):

    duplicates = []

    seen = {}

    for feature in features:

        values = pd.util.hash_pandas_object(
            df[feature],
            index=False
        ).values.tobytes()

        if values in seen:

            duplicates.append(
                (feature, seen[values])
            )

        else:

            seen[values] = feature

    return duplicates


# ======================================================================
# FINAL NUMERICAL QC
# ======================================================================

def final_numeric_qc(train, test, features):

    print_header("FINAL NUMERICAL QC")

    train_nan = int(
        train[features].isna().sum().sum()
    )

    test_nan = int(
        test[features].isna().sum().sum()
    )

    train_inf = int(
        np.isinf(
            train[features].to_numpy()
        ).sum()
    )

    test_inf = int(
        np.isinf(
            test[features].to_numpy()
        ).sum()
    )

    print(f"Training NaN: {train_nan}")
    print(f"Testing NaN : {test_nan}")

    print(f"Training Inf: {train_inf}")
    print(f"Testing Inf : {test_inf}")

    if train_nan or test_nan:
        fail("NaN values remain in final features.")

    if train_inf or test_inf:
        fail("Inf values remain in final features.")

    print("Final numerical QC: PASS")


# ======================================================================
# SAVE PREPROCESSING STATISTICS
# ======================================================================

def save_preprocessing_statistics(
    train,
    features,
    medians,
    variance_values
):

    rows = []

    for feature in features:

        series = train[feature]

        rows.append({
            "Feature": feature,
            "Train_Median": medians.get(
                feature,
                np.nan
            ),
            "Train_Mean": float(
                series.mean()
            ),
            "Train_Std": float(
                series.std(ddof=0)
            ),
            "Train_Min": float(
                series.min()
            ),
            "Train_Max": float(
                series.max()
            ),
            "Train_Variance": float(
                variance_values.get(
                    feature,
                    series.var(ddof=0)
                )
            )
        })

    stats = pd.DataFrame(rows)

    stats.to_csv(
        PREPROCESSING_OUTPUT,
        sep="\t",
        index=False
    )

    print(
        f"Saved: {PREPROCESSING_OUTPUT}"
    )


# ======================================================================
# SAVE FEATURE REMOVAL LOG
# ======================================================================

def save_removal_log(
    initial_features,
    missing_removed,
    variance_removed,
    correlation_removed
):

    rows = []

    for feature in initial_features:

        if feature in missing_removed:

            reason = "Missingness"

        elif feature in variance_removed:

            reason = "Zero_or_NearZero_Variance"

        elif feature in correlation_removed:

            reason = "High_Correlation"

        else:

            reason = "Retained"

        rows.append({
            "Feature": feature,
            "Status": (
                "Removed"
                if reason != "Retained"
                else "Retained"
            ),
            "Reason": reason
        })

    pd.DataFrame(rows).to_csv(
        REMOVAL_LOG_OUTPUT,
        sep="\t",
        index=False
    )

    print(
        f"Saved: {REMOVAL_LOG_OUTPUT}"
    )


# ======================================================================
# SAVE FINAL FEATURE LIST
# ======================================================================

def save_feature_list(features):

    with open(
        FEATURE_LIST_OUTPUT,
        "w"
    ) as f:

        for feature in features:
            f.write(feature + "\n")

    print(
        f"Saved: {FEATURE_LIST_OUTPUT}"
    )


# ======================================================================
# SAVE REMOVED FEATURES
# ======================================================================

def save_removed_features(
    missing_removed,
    variance_removed,
    correlation_removed
):

    rows = []

    for feature in missing_removed:

        rows.append(
            f"{feature}\tMissingness"
        )

    for feature in variance_removed:

        rows.append(
            f"{feature}\tZero_or_NearZero_Variance"
        )

    for feature in correlation_removed:

        rows.append(
            f"{feature}\tHigh_Correlation"
        )

    with open(
        REMOVED_FEATURE_OUTPUT,
        "w"
    ) as f:

        f.write(
            "Feature\tRemoval_Reason\n"
        )

        for row in rows:
            f.write(row + "\n")

    print(
        f"Saved: {REMOVED_FEATURE_OUTPUT}"
    )


# ======================================================================
# SAVE QC SUMMARY
# ======================================================================

def save_qc_summary(
    initial_features,
    missing_removed,
    variance_removed,
    correlation_removed,
    final_features,
    train,
    test
):

    with open(
        QC_SUMMARY_OUTPUT,
        "w"
    ) as f:

        f.write(
            "SCRIPT 05 v3 QC SUMMARY\n"
        )

        f.write(
            "========================================\n"
        )

        f.write(
            f"Initial RDKit descriptors: "
            f"{EXPECTED_RDKIT}\n"
        )

        f.write(
            f"Initial 3D descriptors: "
            f"{EXPECTED_3D}\n"
        )

        f.write(
            f"Initial ML features: "
            f"{len(initial_features)}\n"
        )

        f.write(
            f"Removed by missingness: "
            f"{len(missing_removed)}\n"
        )

        f.write(
            f"Removed by variance: "
            f"{len(variance_removed)}\n"
        )

        f.write(
            f"Removed by correlation: "
            f"{len(correlation_removed)}\n"
        )

        f.write(
            f"Final ML features: "
            f"{len(final_features)}\n"
        )

        f.write("\n")

        f.write(
            f"Training molecules: "
            f"{len(train):,}\n"
        )

        f.write(
            f"Testing molecules: "
            f"{len(test):,}\n"
        )

        f.write("\n")

        f.write(
            f"Training final shape: "
            f"{train.shape}\n"
        )

        f.write(
            f"Testing final shape: "
            f"{test.shape}\n"
        )

        f.write("\n")

        f.write(
            "QC: PASS\n"
        )

    print(
        f"Saved: {QC_SUMMARY_OUTPUT}"
    )


# ======================================================================
# MAIN
# ======================================================================

def main():

    start_time = time.time()

    print_header(
        "SCRIPT 05 v3 — RDKit 217 + 3D 11 FEATURE INTEGRATION"
    )

    print(
        "Expected feature composition:"
    )

    print(
        f"  RDKit descriptors: {EXPECTED_RDKIT}"
    )

    print(
        f"  3D descriptors:    {EXPECTED_3D}"
    )

    print(
        f"  TOTAL:             {EXPECTED_TOTAL}"
    )

    print(
        "\nQC policy:"
    )

    print(
        "  All filtering decisions are based ONLY on TRAIN."
    )

    print(
        "  Test is transformed using TRAIN-derived decisions."
    )

    print(
        "  No scaling performed in this script."
    )

    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True
    )

    # --------------------------------------------------------------
    # FILE CHECK
    # --------------------------------------------------------------

    print_header("CHECKING INPUT FILES")

    input_files = [
        RDKit_TRAIN,
        RDKit_TEST,
        THREE_D_TRAIN,
        THREE_D_TEST,
        DESCRIPTOR_LIST
    ]

    for path in input_files:

        check_file(path)

        print(
            f"FOUND: {path}"
        )

    # --------------------------------------------------------------
    # LOAD
    # --------------------------------------------------------------

    print_header("LOADING INPUT DATASETS")

    rdkit_train = load_tsv(RDKit_TRAIN)
    rdkit_test = load_tsv(RDKit_TEST)

    three_d_train = load_tsv(THREE_D_TRAIN)
    three_d_test = load_tsv(THREE_D_TEST)

    # --------------------------------------------------------------
    # ROW COUNT
    # --------------------------------------------------------------

    print_header("ROW COUNT VALIDATION")

    expected_train = 48152
    expected_test = 12038

    check_row_count(
        rdkit_train,
        expected_train,
        "RDKit TRAIN"
    )

    check_row_count(
        rdkit_test,
        expected_test,
        "RDKit TEST"
    )

    check_row_count(
        three_d_train,
        expected_train,
        "3D TRAIN"
    )

    check_row_count(
        three_d_test,
        expected_test,
        "3D TEST"
    )

    # --------------------------------------------------------------
    # DUPLICATE IDS
    # --------------------------------------------------------------

    print_header("ID VALIDATION")

    check_unique_ids(
        rdkit_train,
        "RDKit TRAIN"
    )

    check_unique_ids(
        rdkit_test,
        "RDKit TEST"
    )

    check_unique_ids(
        three_d_train,
        "3D TRAIN"
    )

    check_unique_ids(
        three_d_test,
        "3D TEST"
    )

    # --------------------------------------------------------------
    # TRAIN TEST LEAKAGE
    # --------------------------------------------------------------

    print_header("TRAIN / TEST LEAKAGE CHECK")

    check_train_test_overlap(
        rdkit_train,
        rdkit_test
    )

    # --------------------------------------------------------------
    # DESCRIPTOR LIST
    # --------------------------------------------------------------

    print_header("LOADING AUTHORITATIVE RDKit DESCRIPTOR LIST")

    descriptor_list = read_descriptor_list(
        DESCRIPTOR_LIST
    )

    print(
        f"RDKit descriptor list: "
        f"{len(descriptor_list)}"
    )

    # --------------------------------------------------------------
    # VALIDATE RDKit
    # --------------------------------------------------------------

    rdkit_features = validate_rdkit_descriptors(
        rdkit_train,
        rdkit_test,
        descriptor_list
    )

    # --------------------------------------------------------------
    # VALIDATE 3D
    # --------------------------------------------------------------

    three_d_features = validate_3d_descriptors(
        three_d_train,
        three_d_test
    )

    # --------------------------------------------------------------
    # ID MATCHING
    # --------------------------------------------------------------

    check_id_matching(
        rdkit_train,
        three_d_train,
        rdkit_test,
        three_d_test
    )

    # --------------------------------------------------------------
    # INITIAL FEATURE LIST
    # --------------------------------------------------------------

    initial_features = (
        rdkit_features
        + three_d_features
    )

    print_header("INITIAL FEATURE COMPOSITION")

    print(
        f"RDKit features: {len(rdkit_features)}"
    )

    print(
        f"3D features:    {len(three_d_features)}"
    )

    print(
        f"TOTAL features: {len(initial_features)}"
    )

    if len(initial_features) != EXPECTED_TOTAL:

        fail(
            f"Expected {EXPECTED_TOTAL} total features "
            f"but found {len(initial_features)}."
        )

    # --------------------------------------------------------------
    # MERGE
    # --------------------------------------------------------------

    print_header("MERGING RDKit + 3D FEATURES")

    train = merge_features(
        rdkit_train,
        three_d_train,
        rdkit_features
    )

    test = merge_features(
        rdkit_test,
        three_d_test,
        rdkit_features
    )

    print(
        f"Merged TRAIN rows: {len(train):,}"
    )

    print(
        f"Merged TEST rows : {len(test):,}"
    )

    # --------------------------------------------------------------
    # TARGET VALIDATION
    # --------------------------------------------------------------

    print_header("TARGET VALIDATION")

    if TARGET_COLUMN not in rdkit_train.columns:

        fail(
            f"Target column missing: {TARGET_COLUMN}"
        )

    train_target = (
        rdkit_train[
            [ID_COLUMN, TARGET_COLUMN]
        ]
        .copy()
    )

    test_target = (
        rdkit_test[
            [ID_COLUMN, TARGET_COLUMN]
        ]
        .copy()
    )

    train = train.merge(
        train_target,
        on=ID_COLUMN,
        how="left",
        validate="one_to_one",
        suffixes=("", "_target")
    )

    test = test.merge(
        test_target,
        on=ID_COLUMN,
        how="left",
        validate="one_to_one",
        suffixes=("", "_target")
    )

    if TARGET_COLUMN + "_target" in train.columns:

        if not (
            train[TARGET_COLUMN]
            == train[TARGET_COLUMN + "_target"]
        ).all():

            fail(
                "TRAIN target mismatch detected."
            )

        train.drop(
            columns=[TARGET_COLUMN + "_target"],
            inplace=True
        )

    if TARGET_COLUMN + "_target" in test.columns:

        if not (
            test[TARGET_COLUMN]
            == test[TARGET_COLUMN + "_target"]
        ).all():

            fail(
                "TEST target mismatch detected."
            )

        test.drop(
            columns=[TARGET_COLUMN + "_target"],
            inplace=True
        )

    print(
        "Target validation: PASS"
    )

    print(
        "\nTraining target distribution:"
    )

    print(
        train[TARGET_COLUMN].value_counts(
            dropna=False
        ).sort_index()
    )

    print(
        "\nTesting target distribution:"
    )

    print(
        test[TARGET_COLUMN].value_counts(
            dropna=False
        ).sort_index()
    )

    # --------------------------------------------------------------
    # NUMERIC CONVERSION
    # --------------------------------------------------------------

    print_header("NUMERIC FEATURE CONVERSION")

    train = force_numeric(
        train,
        initial_features,
        "TRAIN"
    )

    test = force_numeric(
        test,
        initial_features,
        "TEST"
    )

    # --------------------------------------------------------------
    # MISSINGNESS
    # --------------------------------------------------------------

    (
        features_after_missing,
        missing_removed,
        missing_train,
        missing_test
    ) = missingness_qc(
        train,
        test,
        initial_features
    )

    # --------------------------------------------------------------
    # MEDIAN IMPUTATION
    # --------------------------------------------------------------

    train_medians = median_imputation(
        train,
        test,
        features_after_missing
    )

    # --------------------------------------------------------------
    # VARIANCE
    # --------------------------------------------------------------

    (
        features_after_variance,
        variance_removed,
        variance_values
    ) = variance_filter(
        train,
        features_after_missing
    )

    # --------------------------------------------------------------
    # CORRELATION
    # --------------------------------------------------------------

    (
        final_features,
        correlation_removed,
        correlation_pairs
    ) = correlation_filter(
        train,
        features_after_variance
    )

    # --------------------------------------------------------------
    # FINAL FEATURE COUNT
    # --------------------------------------------------------------

    print_header("FINAL FEATURE SELECTION")

    print(
        f"Initial features: "
        f"{len(initial_features)}"
    )

    print(
        f"Removed by missingness: "
        f"{len(missing_removed)}"
    )

    print(
        f"Removed by variance: "
        f"{len(variance_removed)}"
    )

    print(
        f"Removed by correlation: "
        f"{len(correlation_removed)}"
    )

    print(
        f"FINAL FEATURES: "
        f"{len(final_features)}"
    )

    # --------------------------------------------------------------
    # CHECK DUPLICATE FEATURE COLUMNS
    # --------------------------------------------------------------

    print_header("DUPLICATE FEATURE COLUMN CHECK")

    duplicates_train = duplicate_feature_columns(
        train,
        final_features
    )

    duplicates_test = duplicate_feature_columns(
        test,
        final_features
    )

    print(
        f"Training duplicate feature columns: "
        f"{len(duplicates_train)}"
    )

    print(
        f"Testing duplicate feature columns: "
        f"{len(duplicates_test)}"
    )

    if duplicates_train:

        print(
            "WARNING: duplicate feature columns "
            "detected in TRAIN."
        )

    if duplicates_test:

        print(
            "WARNING: duplicate feature columns "
            "detected in TEST."
        )

    # --------------------------------------------------------------
    # FINAL NUMERIC QC
    # --------------------------------------------------------------

    final_numeric_qc(
        train,
        test,
        final_features
    )

    # --------------------------------------------------------------
    # BUILD FINAL DATASETS
    # --------------------------------------------------------------

    print_header("BUILDING FINAL DATASETS")

    # Keep useful identifiers and target.
    output_columns = [
        ID_COLUMN,
        TARGET_COLUMN
    ] + final_features

    # Remove possible duplicate columns.
    output_columns = list(
        dict.fromkeys(output_columns)
    )

    final_train = train[
        output_columns
    ].copy()

    final_test = test[
        output_columns
    ].copy()

    # --------------------------------------------------------------
    # CHECK FEATURE ORDER
    # --------------------------------------------------------------

    train_feature_columns = [
        c for c in final_train.columns
        if c not in [ID_COLUMN, TARGET_COLUMN]
    ]

    test_feature_columns = [
        c for c in final_test.columns
        if c not in [ID_COLUMN, TARGET_COLUMN]
    ]

    if train_feature_columns != test_feature_columns:

        fail(
            "TRAIN/TEST feature ordering mismatch."
        )

    print(
        "TRAIN/TEST feature ordering: PASS"
    )

    # --------------------------------------------------------------
    # FINAL SHAPES
    # --------------------------------------------------------------

    print(
        f"Training final shape: "
        f"{final_train.shape}"
    )

    print(
        f"Testing final shape : "
        f"{final_test.shape}"
    )

    # --------------------------------------------------------------
    # SAVE
    # --------------------------------------------------------------

    print_header("SAVING FINAL DATASETS")

    final_train.to_csv(
        TRAIN_OUTPUT,
        sep="\t",
        index=False
    )

    final_test.to_csv(
        TEST_OUTPUT,
        sep="\t",
        index=False
    )

    print(
        f"Saved: {TRAIN_OUTPUT}"
    )

    print(
        f"Saved: {TEST_OUTPUT}"
    )

    # --------------------------------------------------------------
    # SAVE METADATA
    # --------------------------------------------------------------

    save_feature_list(
        final_features
    )

    save_removed_features(
        missing_removed,
        variance_removed,
        correlation_removed
    )

    save_removal_log(
        initial_features,
        missing_removed,
        variance_removed,
        correlation_removed
    )

    save_preprocessing_statistics(
        train,
        final_features,
        train_medians,
        variance_values
    )

    save_qc_summary(
        initial_features,
        missing_removed,
        variance_removed,
        correlation_removed,
        final_features,
        final_train,
        final_test
    )

    # --------------------------------------------------------------
    # FINAL SUMMARY
    # --------------------------------------------------------------

    runtime = (
        time.time()
        - start_time
    )

    print_header("SCRIPT 05 v3 — FINAL SUMMARY")

    print(
        f"RDKit descriptors: "
        f"{EXPECTED_RDKIT}"
    )

    print(
        f"3D descriptors:    "
        f"{EXPECTED_3D}"
    )

    print(
        f"Initial features:  "
        f"{EXPECTED_TOTAL}"
    )

    print(
        f"Final features:    "
        f"{len(final_features)}"
    )

    print(
        f"Training molecules: "
        f"{len(final_train):,}"
    )

    print(
        f"Testing molecules:  "
        f"{len(final_test):,}"
    )

    print(
        f"Training NaN: "
        f"{int(final_train[final_features].isna().sum().sum())}"
    )

    print(
        f"Testing NaN:  "
        f"{int(final_test[final_features].isna().sum().sum())}"
    )

    print(
        f"Training Inf: "
        f"{int(np.isinf(final_train[final_features].to_numpy()).sum())}"
    )

    print(
        f"Testing Inf:  "
        f"{int(np.isinf(final_test[final_features].to_numpy()).sum())}"
    )

    print()
    print(
        "FINAL QC: PASS"
    )

    print()
    print(
        f"Runtime: {runtime / 60:.2f} minutes"
    )

    print()
    print(
        "OUTPUT FILES:"
    )

    print(
        TRAIN_OUTPUT
    )

    print(
        TEST_OUTPUT
    )

    print(
        FEATURE_LIST_OUTPUT
    )

    print(
        REMOVED_FEATURE_OUTPUT
    )

    print(
        PREPROCESSING_OUTPUT
    )

    print(
        QC_SUMMARY_OUTPUT
    )

    print(
        REMOVAL_LOG_OUTPUT
    )

    print()
    print("=" * 78)
    print("SCRIPT 05 v3 COMPLETED SUCCESSFULLY")
    print("=" * 78)


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":
    main()
