#!/usr/bin/env python3

"""
===============================================================================
SCRIPT 08 v2 — TARGET / OFF-TARGET VALIDATION PERFORMANCE FIGURE GENERATOR
===============================================================================

Purpose
-------
Generate publication-grade performance plots for the 40D target/off-target
inference engine using the actual validation datasets generated by Script 06.

This script is NOT a single-query visualization script.

Primary validation sources
--------------------------
06_target_recovery.tsv
06_neighbor_recovery.tsv
06_offtarget_recovery.tsv
06_similarity_threshold_summary.tsv
06_validation_summary.tsv
06_target_annotation_qc.tsv

Additional supporting sources
-----------------------------
target_inference_reference_annotations.tsv
target_inference_associations_annotated.tsv
target_id_resolution_final.tsv

Main outputs
------------
01_similarity_threshold_recovery
02_top_k_target_recovery
03_neighbor_recovery
04_target_vs_offtarget_recovery
05_target_ranking_performance
06_similarity_distribution
07_target_hierarchy_recovery
08_candidate_burden_vs_threshold
09_validation_summary
10_target_annotation_coverage

Each figure is exported as:
    PNG 300 dpi
    PDF
    SVG

No artificial data are generated.
No missing metrics are imputed.
No empty figures are produced.

===============================================================================
"""

from __future__ import annotations

import json
import math
import re
import sys
import traceback
from datetime import datetime
from pathlib import Path
from typing import Optional, Iterable

import numpy as np
import pandas as pd

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


# =============================================================================
# CONFIGURATION
# =============================================================================

BASE_DIR = Path("/lustre/home/sklab202/sourav/PULP")

VALIDATION_DIR = (
    BASE_DIR
    / "target_model"
    / "validation"
    / "06_40d_target_offtarget_validation"
)

INFERENCE_DIR = (
    BASE_DIR
    / "target_model"
    / "inference"
    / "07_query_40d_target_offtarget"
)

RESOLUTION_DIR = (
    BASE_DIR
    / "target_model"
    / "data"
    / "03_target_resolution"
)

OUTPUT_DIR = (
    BASE_DIR
    / "target_model"
    / "plots"
    / "08_target_offtarget_validation"
)

FIGURE_DPI = 300

FIGURE_WIDTH = 8.5
FIGURE_HEIGHT = 6.0

TOP_K_VALUES = [1, 3, 5, 10, 20, 30, 50]

MAX_LABELS = 20

RANDOM_STATE = 42


# =============================================================================
# FILE DEFINITIONS
# =============================================================================

FILES = {
    "target_recovery": VALIDATION_DIR / "06_target_recovery.tsv",
    "neighbor_recovery": VALIDATION_DIR / "06_neighbor_recovery.tsv",
    "offtarget_recovery": VALIDATION_DIR / "06_offtarget_recovery.tsv",
    "threshold_summary": VALIDATION_DIR / "06_similarity_threshold_summary.tsv",
    "validation_summary": VALIDATION_DIR / "06_validation_summary.tsv",
    "target_annotation_qc": VALIDATION_DIR / "06_target_annotation_qc.tsv",
    "target_reference_annotations": (
        RESOLUTION_DIR / "target_inference_reference_annotations.tsv"
    ),
    "target_associations": (
        RESOLUTION_DIR / "target_inference_associations_annotated.tsv"
    ),
    "target_resolution": (
        RESOLUTION_DIR / "target_id_resolution_final.tsv"
    ),
}


# =============================================================================
# LOGGING
# =============================================================================

LOG_LINES = []

GENERATED = []
SKIPPED = []
ERRORS = []


def log(message: str) -> None:
    print(message)
    LOG_LINES.append(message)


def section(title: str) -> None:
    line = "=" * 78
    log("")
    log(line)
    log(title)
    log(line)


# =============================================================================
# GENERAL HELPERS
# =============================================================================

def norm(text) -> str:
    """
    Normalize a column name for matching.
    """
    text = str(text).strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")


def clean_numeric(series: pd.Series) -> pd.Series:
    """
    Convert a Series to numeric without inventing values.
    """
    return pd.to_numeric(series, errors="coerce")


def is_numeric_series(series: pd.Series, minimum_fraction: float = 0.70) -> bool:
    """
    Check whether enough values can be interpreted numerically.
    """
    if series.empty:
        return False

    numeric = pd.to_numeric(series, errors="coerce")
    return numeric.notna().mean() >= minimum_fraction


def find_column(
    df: pd.DataFrame,
    exact: Iterable[str] = (),
    contains_all: Iterable[str] = (),
    contains_any: Iterable[str] = (),
    exclude: Iterable[str] = (),
) -> Optional[str]:

    normalized = {c: norm(c) for c in df.columns}

    exact_norm = {norm(x) for x in exact}
    contains_all_norm = [norm(x) for x in contains_all]
    contains_any_norm = [norm(x) for x in contains_any]
    exclude_norm = [norm(x) for x in exclude]

    # Exact match first.
    for col, ncol in normalized.items():
        if ncol in exact_norm:
            return col

    # All tokens.
    if contains_all_norm:
        for col, ncol in normalized.items():
            if all(token in ncol for token in contains_all_norm):
                if not any(token in ncol for token in exclude_norm):
                    return col

    # Any token.
    if contains_any_norm:
        for col, ncol in normalized.items():
            if any(token in ncol for token in contains_any_norm):
                if not any(token in ncol for token in exclude_norm):
                    return col

    return None


def find_numeric_columns(df: pd.DataFrame) -> list[str]:
    return [
        c
        for c in df.columns
        if is_numeric_series(df[c])
    ]


def read_tsv(path: Path) -> Optional[pd.DataFrame]:

    if not path.exists():
        SKIPPED.append(f"MISSING FILE: {path}")
        log(f"WARNING | Missing: {path}")
        return None

    try:
        df = pd.read_csv(path, sep="\t", low_memory=False)

        log(
            f"LOADED | {path.name} | "
            f"rows={len(df):,} | cols={len(df.columns)}"
        )

        log(
            "         columns = "
            + ", ".join(str(c) for c in df.columns)
        )

        return df

    except Exception as exc:
        ERRORS.append(f"{path}: {exc}")
        log(f"ERROR | Failed reading {path}: {exc}")
        return None


# =============================================================================
# PLOTTING STYLE
# =============================================================================

def apply_publication_style() -> None:

    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": FIGURE_DPI,
            "font.size": 11,
            "axes.titlesize": 14,
            "axes.labelsize": 12,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 10,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "figure.autolayout": True,
        }
    )


def save_figure(fig: plt.Figure, stem: str) -> None:

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    paths = []

    for extension in ["png", "pdf", "svg"]:

        output = OUTPUT_DIR / f"{stem}.{extension}"

        if extension == "png":
            fig.savefig(
                output,
                dpi=FIGURE_DPI,
                bbox_inches="tight",
            )
        else:
            fig.savefig(
                output,
                bbox_inches="tight",
            )

        paths.append(str(output))

    plt.close(fig)

    GENERATED.append(
        {
            "figure": stem,
            "files": paths,
        }
    )

    log(
        f"GENERATED | {stem} | "
        f"PNG + PDF + SVG"
    )


def skip_figure(stem: str, reason: str) -> None:

    SKIPPED.append(
        f"{stem}: {reason}"
    )

    log(
        f"SKIP | {stem} | {reason}"
    )


# =============================================================================
# BOOLEAN / RECOVERY HELPERS
# =============================================================================

TRUE_VALUES = {
    "true",
    "1",
    "yes",
    "y",
    "recovered",
    "hit",
    "success",
    "present",
    "found",
}

FALSE_VALUES = {
    "false",
    "0",
    "no",
    "n",
    "not_recovered",
    "miss",
    "failed",
    "absent",
    "not_found",
}


def to_boolean(series: pd.Series) -> pd.Series:

    def convert(value):

        if pd.isna(value):
            return np.nan

        if isinstance(value, (bool, np.bool_)):
            return bool(value)

        if isinstance(value, (int, float, np.integer, np.floating)):
            if value == 1:
                return True
            if value == 0:
                return False

        value_norm = norm(value)

        if value_norm in TRUE_VALUES:
            return True

        if value_norm in FALSE_VALUES:
            return False

        return np.nan

    return series.map(convert)


def find_recovery_column(df: pd.DataFrame) -> Optional[str]:

    exact = [
        "Recovered",
        "Recovery",
        "Target_Recovered",
        "Offtarget_Recovered",
        "Off_Target_Recovered",
        "Neighbor_Recovered",
        "Recovery_Status",
        "Hit",
        "Target_Hit",
    ]

    col = find_column(df, exact=exact)

    if col is not None:
        return col

    for c in df.columns:

        n = norm(c)

        if "recover" in n or "hit" in n:

            # Avoid columns such as "recovery_rank".
            if "rank" not in n and "count" not in n:
                return c

    return None


def derive_recovery_boolean(df: pd.DataFrame) -> Optional[pd.Series]:

    recovery_col = find_recovery_column(df)

    if recovery_col is not None:

        boolean = to_boolean(df[recovery_col])

        if boolean.notna().sum() > 0:
            return boolean

    # Some validation files may encode recovery using rank.
    rank_col = find_column(
        df,
        exact=[
            "Target_Rank",
            "Recovered_Target_Rank",
            "Hit_Rank",
            "Rank",
        ],
    )

    if rank_col is not None:

        rank = clean_numeric(df[rank_col])

        return rank.notna()

    return None


# =============================================================================
# SIMILARITY COLUMN
# =============================================================================

def find_similarity_column(df: pd.DataFrame) -> Optional[str]:

    exact = [
        "Similarity",
        "Cosine_Similarity",
        "CosineSimilarity",
        "Similarity_Score",
        "Max_Similarity",
        "Best_Similarity",
        "Nearest_Similarity",
    ]

    col = find_column(df, exact=exact)

    if col is not None:
        return col

    for c in df.columns:

        n = norm(c)

        if "similarity" in n or "cosine" in n:

            if is_numeric_series(df[c]):
                return c

    return None


# =============================================================================
# RANK COLUMN
# =============================================================================

def find_rank_column(df: pd.DataFrame) -> Optional[str]:

    exact = [
        "Rank",
        "Neighbor_Rank",
        "Target_Rank",
        "Candidate_Rank",
        "Reference_Rank",
        "Top_K_Rank",
    ]

    col = find_column(df, exact=exact)

    if col is not None:
        return col

    for c in df.columns:

        n = norm(c)

        if "rank" in n and is_numeric_series(df[c]):
            return c

    return None


# =============================================================================
# QUERY / MOLECULE ID
# =============================================================================

def find_query_column(df: pd.DataFrame) -> Optional[str]:

    exact = [
        "Query_ID",
        "Query_Molecule",
        "Molecule_ID",
        "NP_ID",
        "Compound_ID",
        "Query",
        "Molecule",
    ]

    return find_column(df, exact=exact)


# =============================================================================
# TARGET ID COLUMN
# =============================================================================

def find_target_column(df: pd.DataFrame) -> Optional[str]:

    exact = [
        "Target_ID",
        "Target",
        "TargetID",
        "Gene",
        "Gene_Symbol",
        "Protein",
        "Protein_Name",
    ]

    col = find_column(df, exact=exact)

    if col is not None:
        return col

    for c in df.columns:

        n = norm(c)

        if "target" in n and "count" not in n:

            return c

    return None


# =============================================================================
# FIGURE 01
# =============================================================================

def figure_01_similarity_threshold_recovery(
    threshold_df: Optional[pd.DataFrame],
) -> None:

    stem = "01_similarity_threshold_recovery"

    if threshold_df is None or threshold_df.empty:
        skip_figure(stem, "06_similarity_threshold_summary.tsv unavailable")
        return

    threshold_col = find_column(
        threshold_df,
        exact=[
            "Similarity_Threshold",
            "Threshold",
            "Cosine_Threshold",
            "SimilarityThreshold",
        ],
    )

    if threshold_col is None:

        # Search numeric columns whose name contains threshold.
        for c in threshold_df.columns:
            if "threshold" in norm(c) and is_numeric_series(threshold_df[c]):
                threshold_col = c
                break

    if threshold_col is None:
        skip_figure(stem, "similarity-threshold column unavailable")
        return

    threshold = clean_numeric(threshold_df[threshold_col])

    metric_columns = []

    for c in threshold_df.columns:

        if c == threshold_col:
            continue

        if not is_numeric_series(threshold_df[c]):
            continue

        n = norm(c)

        if any(
            token in n
            for token in [
                "recall",
                "recovery",
                "precision",
                "coverage",
                "hit_rate",
                "sensitivity",
                "candidate",
                "retrieval",
            ]
        ):
            metric_columns.append(c)

    if not metric_columns:

        skip_figure(
            stem,
            "no supported numeric recovery/coverage metrics found",
        )
        return

    plot_df = threshold_df[[threshold_col] + metric_columns].copy()
    plot_df[threshold_col] = threshold

    plot_df = plot_df.dropna(subset=[threshold_col])
    plot_df = plot_df.sort_values(threshold_col)

    if plot_df.empty:
        skip_figure(stem, "no valid threshold observations")
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    plotted = 0

    for col in metric_columns:

        y = clean_numeric(plot_df[col])

        valid = y.notna()

        if valid.sum() < 2:
            continue

        ax.plot(
            plot_df.loc[valid, threshold_col],
            y.loc[valid],
            marker="o",
            linewidth=2,
            label=str(col),
        )

        plotted += 1

    if plotted == 0:

        plt.close(fig)

        skip_figure(
            stem,
            "no metric contained at least two numeric observations",
        )
        return

    ax.set_xlabel("40D cosine similarity threshold")
    ax.set_ylabel("Validation metric")
    ax.set_title(
        "Target/off-target recovery across similarity thresholds"
    )

    ax.grid(
        axis="both",
        alpha=0.25,
        linewidth=0.8,
    )

    ax.legend(
        frameon=False,
        loc="best",
    )

    save_figure(fig, stem)


# =============================================================================
# TOP-K CURVE GENERATOR
# =============================================================================

def calculate_top_k_recovery(
    df: pd.DataFrame,
    rank_col: str,
    recovery: pd.Series,
) -> Optional[pd.DataFrame]:

    ranks = clean_numeric(df[rank_col])

    working = pd.DataFrame(
        {
            "rank": ranks,
            "recovered": recovery,
        }
    )

    working = working.dropna(subset=["rank", "recovered"])

    if working.empty:
        return None

    rows = []

    for k in TOP_K_VALUES:

        subset = working[working["rank"] <= k]

        if subset.empty:
            continue

        rows.append(
            {
                "Top_K": k,
                "Recovery": subset["recovered"].astype(bool).mean(),
                "N": len(subset),
            }
        )

    if not rows:
        return None

    return pd.DataFrame(rows)


def figure_02_top_k_target_recovery(
    target_df: Optional[pd.DataFrame],
) -> None:

    stem = "02_top_k_target_recovery"

    if target_df is None or target_df.empty:
        skip_figure(stem, "06_target_recovery.tsv unavailable")
        return

    rank_col = find_rank_column(target_df)

    if rank_col is None:
        skip_figure(stem, "target rank column unavailable")
        return

    recovery = derive_recovery_boolean(target_df)

    if recovery is None:
        skip_figure(stem, "target recovery indicator unavailable")
        return

    result = calculate_top_k_recovery(
        target_df,
        rank_col,
        recovery,
    )

    if result is None or result.empty:
        skip_figure(stem, "could not calculate top-k recovery")
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.plot(
        result["Top_K"],
        result["Recovery"],
        marker="o",
        linewidth=2.5,
    )

    ax.set_xlabel("Top-k target rank")
    ax.set_ylabel("Recovery fraction")
    ax.set_title(
        "Known-target recovery as a function of ranking depth"
    )

    ax.set_xticks(result["Top_K"])

    ax.set_ylim(
        max(0, result["Recovery"].min() - 0.05),
        min(1, result["Recovery"].max() + 0.05),
    )

    ax.grid(
        axis="both",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 03 — NEIGHBOR RECOVERY
# =============================================================================

def figure_03_neighbor_recovery(
    neighbor_df: Optional[pd.DataFrame],
) -> None:

    stem = "03_neighbor_recovery"

    if neighbor_df is None or neighbor_df.empty:
        skip_figure(stem, "06_neighbor_recovery.tsv unavailable")
        return

    rank_col = find_rank_column(neighbor_df)

    if rank_col is None:
        skip_figure(stem, "neighbor rank column unavailable")
        return

    recovery = derive_recovery_boolean(neighbor_df)

    if recovery is None:
        skip_figure(stem, "neighbor recovery indicator unavailable")
        return

    result = calculate_top_k_recovery(
        neighbor_df,
        rank_col,
        recovery,
    )

    if result is None or result.empty:
        skip_figure(stem, "could not calculate neighbor recovery")
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.plot(
        result["Top_K"],
        result["Recovery"],
        marker="o",
        linewidth=2.5,
    )

    ax.set_xlabel("Number of retrieved neighbors")
    ax.set_ylabel("Recovery fraction")
    ax.set_title(
        "Reference-neighbor recovery with increasing retrieval depth"
    )

    ax.set_xticks(result["Top_K"])

    ax.grid(
        axis="both",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 04 — TARGET VS OFF-TARGET
# =============================================================================

def figure_04_target_vs_offtarget(
    target_df: Optional[pd.DataFrame],
    off_df: Optional[pd.DataFrame],
) -> None:

    stem = "04_target_vs_offtarget_recovery"

    if target_df is None or off_df is None:
        skip_figure(
            stem,
            "target and/or off-target validation table unavailable",
        )
        return

    rank_target = find_rank_column(target_df)
    rank_off = find_rank_column(off_df)

    if rank_target is None or rank_off is None:
        skip_figure(
            stem,
            "rank column unavailable in one or both validation tables",
        )
        return

    rec_target = derive_recovery_boolean(target_df)
    rec_off = derive_recovery_boolean(off_df)

    if rec_target is None or rec_off is None:
        skip_figure(
            stem,
            "recovery indicator unavailable in one or both tables",
        )
        return

    target_curve = calculate_top_k_recovery(
        target_df,
        rank_target,
        rec_target,
    )

    off_curve = calculate_top_k_recovery(
        off_df,
        rank_off,
        rec_off,
    )

    if target_curve is None or off_curve is None:
        skip_figure(
            stem,
            "could not calculate target/off-target recovery curves",
        )
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.plot(
        target_curve["Top_K"],
        target_curve["Recovery"],
        marker="o",
        linewidth=2.5,
        label="Known-target recovery",
    )

    ax.plot(
        off_curve["Top_K"],
        off_curve["Recovery"],
        marker="s",
        linewidth=2.5,
        label="Reference off-target recovery",
    )

    ax.set_xlabel("Top-k ranking depth")
    ax.set_ylabel("Recovery fraction")
    ax.set_title(
        "Target and reference off-target recovery"
    )

    ax.set_xticks(TOP_K_VALUES)

    ax.grid(
        axis="both",
        alpha=0.25,
    )

    ax.legend(frameon=False)

    save_figure(fig, stem)


# =============================================================================
# FIGURE 05 — RANKING PERFORMANCE
# =============================================================================

def figure_05_target_ranking_performance(
    target_df: Optional[pd.DataFrame],
) -> None:

    stem = "05_target_ranking_performance"

    if target_df is None or target_df.empty:
        skip_figure(stem, "target recovery table unavailable")
        return

    rank_col = find_rank_column(target_df)

    if rank_col is None:
        skip_figure(stem, "target rank column unavailable")
        return

    ranks = clean_numeric(target_df[rank_col]).dropna()

    if ranks.empty:
        skip_figure(stem, "no valid target ranks")
        return

    ranks = ranks[ranks > 0]

    if ranks.empty:
        skip_figure(stem, "target ranks contain no positive values")
        return

    # Calculate cumulative fraction recovered by rank.
    max_rank = int(min(50, ranks.max()))

    rank_values = np.arange(
        1,
        max_rank + 1,
    )

    recovery = [
        float((ranks <= k).mean())
        for k in rank_values
    ]

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.plot(
        rank_values,
        recovery,
        linewidth=2.5,
    )

    ax.scatter(
        TOP_K_VALUES,
        [
            recovery[k - 1]
            if k <= len(recovery)
            else np.nan
            for k in TOP_K_VALUES
        ],
        s=45,
    )

    ax.set_xlabel("Target rank")
    ax.set_ylabel("Cumulative fraction")
    ax.set_title(
        "Cumulative target-ranking performance"
    )

    ax.set_xlim(
        1,
        max_rank,
    )

    ax.set_ylim(
        0,
        min(1, max(recovery) + 0.05),
    )

    ax.grid(
        axis="both",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 06 — SIMILARITY DISTRIBUTION
# =============================================================================

def figure_06_similarity_distribution(
    target_df: Optional[pd.DataFrame],
) -> None:

    stem = "06_similarity_distribution"

    if target_df is None or target_df.empty:
        skip_figure(stem, "target recovery table unavailable")
        return

    similarity_col = find_similarity_column(target_df)

    if similarity_col is None:
        skip_figure(stem, "similarity column unavailable")
        return

    similarity = clean_numeric(
        target_df[similarity_col]
    )

    valid = similarity.notna()

    if valid.sum() < 10:
        skip_figure(
            stem,
            "fewer than 10 valid similarity observations",
        )
        return

    recovery = derive_recovery_boolean(target_df)

    if recovery is None:
        skip_figure(
            stem,
            "recovery indicator unavailable",
        )
        return

    plot_df = pd.DataFrame(
        {
            "Similarity": similarity,
            "Recovered": recovery,
        }
    ).dropna()

    if plot_df.empty:
        skip_figure(
            stem,
            "no complete similarity/recovery observations",
        )
        return

    recovered = plot_df.loc[
        plot_df["Recovered"].astype(bool),
        "Similarity",
    ]

    not_recovered = plot_df.loc[
        ~plot_df["Recovered"].astype(bool),
        "Similarity",
    ]

    if len(recovered) < 2 or len(not_recovered) < 2:
        skip_figure(
            stem,
            "both recovered and non-recovered groups require at least two observations",
        )
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.hist(
        recovered,
        bins=30,
        alpha=0.60,
        density=True,
        label="Recovered",
    )

    ax.hist(
        not_recovered,
        bins=30,
        alpha=0.60,
        density=True,
        label="Not recovered",
    )

    ax.set_xlabel("40D cosine similarity")
    ax.set_ylabel("Density")
    ax.set_title(
        "Similarity distributions for recovered and non-recovered targets"
    )

    ax.legend(frameon=False)

    ax.grid(
        axis="y",
        alpha=0.20,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 07 — TARGET HIERARCHY RECOVERY
# =============================================================================

def find_hierarchy_columns(df: pd.DataFrame) -> list[str]:

    hierarchy = []

    preferred = [
        "Class_1",
        "Class_Level1",
        "Class_Level_1",
        "Class_2",
        "Class_Level2",
        "Class_Level_2",
        "Class_3",
        "Class_Level3",
        "Class_Level_3",
        "Protein",
        "Protein_Name",
        "Gene",
        "Gene_Symbol",
    ]

    for wanted in preferred:

        col = find_column(
            df,
            exact=[wanted],
        )

        if col is not None and col not in hierarchy:
            hierarchy.append(col)

    return hierarchy


def figure_07_target_hierarchy_recovery(
    target_df: Optional[pd.DataFrame],
) -> None:

    stem = "07_target_hierarchy_recovery"

    if target_df is None or target_df.empty:
        skip_figure(stem, "target recovery table unavailable")
        return

    recovery = derive_recovery_boolean(target_df)

    if recovery is None:
        skip_figure(
            stem,
            "target recovery indicator unavailable",
        )
        return

    hierarchy_cols = find_hierarchy_columns(target_df)

    if not hierarchy_cols:
        skip_figure(
            stem,
            "target hierarchy columns unavailable",
        )
        return

    values = []

    recovered_mask = recovery.astype(bool)

    for col in hierarchy_cols:

        total = target_df[col].notna().sum()

        if total == 0:
            continue

        recovered = (
            target_df.loc[
                recovered_mask,
                col,
            ].notna().sum()
        )

        values.append(
            {
                "Level": str(col),
                "Recovery": recovered / total,
                "N": int(total),
            }
        )

    if len(values) < 2:
        skip_figure(
            stem,
            "insufficient hierarchy levels for comparison",
        )
        return

    result = pd.DataFrame(values)

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.bar(
        result["Level"],
        result["Recovery"],
    )

    ax.set_xlabel("Target annotation level")
    ax.set_ylabel("Recovered fraction")
    ax.set_title(
        "Recovery across target annotation hierarchy"
    )

    ax.set_ylim(
        0,
        min(
            1,
            result["Recovery"].max() + 0.10,
        ),
    )

    ax.tick_params(
        axis="x",
        rotation=35,
    )

    ax.grid(
        axis="y",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 08 — CANDIDATE BURDEN VS THRESHOLD
# =============================================================================

def figure_08_candidate_burden(
    threshold_df: Optional[pd.DataFrame],
) -> None:

    stem = "08_candidate_burden_vs_threshold"

    if threshold_df is None or threshold_df.empty:
        skip_figure(
            stem,
            "06_similarity_threshold_summary.tsv unavailable",
        )
        return

    threshold_col = find_column(
        threshold_df,
        exact=[
            "Similarity_Threshold",
            "Threshold",
            "Cosine_Threshold",
        ],
    )

    if threshold_col is None:
        skip_figure(
            stem,
            "threshold column unavailable",
        )
        return

    candidate_col = None

    for c in threshold_df.columns:

        n = norm(c)

        if (
            "candidate" in n
            and is_numeric_series(threshold_df[c])
        ):
            candidate_col = c
            break

        if (
            "retrieved" in n
            and "count" in n
            and is_numeric_series(threshold_df[c])
        ):
            candidate_col = c
            break

    if candidate_col is None:
        skip_figure(
            stem,
            "candidate-count metric unavailable",
        )
        return

    x = clean_numeric(
        threshold_df[threshold_col]
    )

    y = clean_numeric(
        threshold_df[candidate_col]
    )

    valid = x.notna() & y.notna()

    if valid.sum() < 2:
        skip_figure(
            stem,
            "fewer than two valid threshold/candidate observations",
        )
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.plot(
        x.loc[valid],
        y.loc[valid],
        marker="o",
        linewidth=2.5,
    )

    ax.set_xlabel("40D cosine similarity threshold")
    ax.set_ylabel("Candidate count")
    ax.set_title(
        "Candidate burden across similarity thresholds"
    )

    ax.grid(
        axis="both",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 09 — VALIDATION SUMMARY
# =============================================================================

def figure_09_validation_summary(
    validation_df: Optional[pd.DataFrame],
) -> None:

    stem = "09_validation_summary"

    if validation_df is None or validation_df.empty:
        skip_figure(
            stem,
            "06_validation_summary.tsv unavailable",
        )
        return

    numeric_cols = find_numeric_columns(
        validation_df
    )

    if not numeric_cols:
        skip_figure(
            stem,
            "validation summary contains no numeric metrics",
        )
        return

    # Identify a metric/name column.
    metric_col = find_column(
        validation_df,
        exact=[
            "Metric",
            "Measure",
            "Statistic",
            "Validation_Metric",
            "Summary_Metric",
        ],
    )

    value_col = None

    if metric_col is not None:

        candidates = [
            c
            for c in numeric_cols
            if c != metric_col
        ]

        if len(candidates) == 1:
            value_col = candidates[0]

    # If there is no obvious long-format structure, skip rather
    # than generating an arbitrary plot.
    if metric_col is None or value_col is None:

        skip_figure(
            stem,
            "validation summary is not in a supported metric/value format",
        )
        return

    plot_df = validation_df[
        [metric_col, value_col]
    ].copy()

    plot_df[value_col] = clean_numeric(
        plot_df[value_col]
    )

    plot_df = plot_df.dropna()

    if plot_df.empty:
        skip_figure(
            stem,
            "no numeric metric/value observations",
        )
        return

    plot_df = plot_df.head(
        min(MAX_LABELS, len(plot_df))
    )

    fig_height = max(
        FIGURE_HEIGHT,
        0.35 * len(plot_df),
    )

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, fig_height)
    )

    y = np.arange(len(plot_df))

    ax.barh(
        y,
        plot_df[value_col],
    )

    ax.set_yticks(y)

    ax.set_yticklabels(
        plot_df[metric_col].astype(str)
    )

    ax.invert_yaxis()

    ax.set_xlabel(str(value_col))
    ax.set_title(
        "Target/off-target validation summary"
    )

    ax.grid(
        axis="x",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# FIGURE 10 — TARGET ANNOTATION COVERAGE
# =============================================================================

def figure_10_annotation_coverage(
    annotation_qc_df: Optional[pd.DataFrame],
) -> None:

    stem = "10_target_annotation_coverage"

    if annotation_qc_df is None or annotation_qc_df.empty:
        skip_figure(
            stem,
            "06_target_annotation_qc.tsv unavailable",
        )
        return

    numeric_cols = find_numeric_columns(
        annotation_qc_df
    )

    if not numeric_cols:
        skip_figure(
            stem,
            "annotation QC contains no numeric metrics",
        )
        return

    # Find a descriptive category column.
    category_col = None

    for c in annotation_qc_df.columns:

        if c in numeric_cols:
            continue

        if annotation_qc_df[c].nunique(dropna=True) >= 2:
            category_col = c
            break

    if category_col is None:
        skip_figure(
            stem,
            "no categorical annotation-QC dimension available",
        )
        return

    # Select the first meaningful numeric metric.
    metric_col = None

    preferred = [
        "Coverage",
        "Annotation_Coverage",
        "Fraction",
        "Count",
        "N",
        "Number",
    ]

    for wanted in preferred:

        col = find_column(
            annotation_qc_df,
            exact=[wanted],
        )

        if col in numeric_cols:
            metric_col = col
            break

    if metric_col is None:
        metric_col = numeric_cols[0]

    plot_df = annotation_qc_df[
        [category_col, metric_col]
    ].copy()

    plot_df[metric_col] = clean_numeric(
        plot_df[metric_col]
    )

    plot_df = plot_df.dropna()

    if plot_df.empty:
        skip_figure(
            stem,
            "no valid annotation-QC observations",
        )
        return

    fig, ax = plt.subplots(
        figsize=(FIGURE_WIDTH, FIGURE_HEIGHT)
    )

    ax.bar(
        plot_df[category_col].astype(str),
        plot_df[metric_col],
    )

    ax.set_xlabel(str(category_col))
    ax.set_ylabel(str(metric_col))
    ax.set_title(
        "Target annotation coverage in validation data"
    )

    ax.tick_params(
        axis="x",
        rotation=35,
    )

    ax.grid(
        axis="y",
        alpha=0.25,
    )

    save_figure(fig, stem)


# =============================================================================
# SCHEMA REPORT
# =============================================================================

def write_schema_report(
    tables: dict[str, Optional[pd.DataFrame]]
) -> None:

    report_path = OUTPUT_DIR / "08_validation_schema_report.tsv"

    rows = []

    for name, df in tables.items():

        if df is None:
            rows.append(
                {
                    "Table": name,
                    "Rows": np.nan,
                    "Columns": np.nan,
                    "Column_Name": "",
                    "Detected_Type": "MISSING",
                }
            )
            continue

        for col in df.columns:

            dtype = str(df[col].dtype)

            rows.append(
                {
                    "Table": name,
                    "Rows": len(df),
                    "Columns": len(df.columns),
                    "Column_Name": str(col),
                    "Detected_Type": dtype,
                }
            )

    pd.DataFrame(rows).to_csv(
        report_path,
        sep="\t",
        index=False,
    )

    log(
        f"WRITTEN | {report_path}"
    )


# =============================================================================
# METRIC EXTRACTION TABLE
# =============================================================================

def write_derived_metrics(
    target_df: Optional[pd.DataFrame],
    neighbor_df: Optional[pd.DataFrame],
    off_df: Optional[pd.DataFrame],
) -> None:

    rows = []

    datasets = [
        ("target_recovery", target_df),
        ("neighbor_recovery", neighbor_df),
        ("offtarget_recovery", off_df),
    ]

    for name, df in datasets:

        if df is None or df.empty:
            continue

        rank_col = find_rank_column(df)

        recovery = derive_recovery_boolean(df)

        similarity_col = find_similarity_column(df)

        row = {
            "Dataset": name,
            "Rows": len(df),
            "Rank_Column": rank_col or "",
            "Similarity_Column": similarity_col or "",
            "Recovery_Column": (
                find_recovery_column(df) or ""
            ),
        }

        if recovery is not None:

            valid = recovery.notna()

            row["Recovery_Observations"] = int(
                valid.sum()
            )

            if valid.sum() > 0:
                row["Recovery_Fraction"] = float(
                    recovery.loc[valid].astype(bool).mean()
                )

        if rank_col is not None:

            rank = clean_numeric(
                df[rank_col]
            ).dropna()

            if not rank.empty:
                row["Median_Rank"] = float(
                    rank.median()
                )

                row["Mean_Rank"] = float(
                    rank.mean()
                )

        if similarity_col is not None:

            similarity = clean_numeric(
                df[similarity_col]
            ).dropna()

            if not similarity.empty:

                row["Mean_Similarity"] = float(
                    similarity.mean()
                )

                row["Median_Similarity"] = float(
                    similarity.median()
                )

        rows.append(row)

    if not rows:
        log(
            "No derived validation metrics could be calculated."
        )
        return

    output = OUTPUT_DIR / "08_derived_validation_metrics.tsv"

    pd.DataFrame(rows).to_csv(
        output,
        sep="\t",
        index=False,
    )

    log(
        f"WRITTEN | {output}"
    )


# =============================================================================
# MANIFEST
# =============================================================================

def write_manifest() -> None:

    manifest = {
        "script": "08_target_offtarget_validation_figures.py",
        "version": "v2",
        "created": datetime.now().astimezone().isoformat(),
        "base_directory": str(BASE_DIR),
        "validation_directory": str(VALIDATION_DIR),
        "inference_directory": str(INFERENCE_DIR),
        "output_directory": str(OUTPUT_DIR),
        "figure_dpi": FIGURE_DPI,
        "top_k_values": TOP_K_VALUES,
        "generated_figures": GENERATED,
        "skipped_figures": SKIPPED,
        "errors": ERRORS,
        "principles": [
            "Validation tables are used instead of single-query examples.",
            "No synthetic observations are generated.",
            "No missing performance metric is imputed.",
            "Figures are skipped when required columns are unavailable.",
            "PNG, PDF and SVG versions are generated for every successful figure.",
        ],
    }

    path = OUTPUT_DIR / "08_target_offtarget_validation_plot_manifest.json"

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as handle:

        json.dump(
            manifest,
            handle,
            indent=2,
        )

    log(
        f"WRITTEN | {path}"
    )


# =============================================================================
# MAIN
# =============================================================================

def main() -> int:

    start = datetime.now().astimezone()

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    apply_publication_style()

    section(
        "SCRIPT 08 v2 — TARGET/OFF-TARGET VALIDATION PERFORMANCE"
    )

    log(
        f"Start time        : {start.isoformat()}"
    )

    log(
        f"Validation dir    : {VALIDATION_DIR}"
    )

    log(
        f"Output directory  : {OUTPUT_DIR}"
    )

    # -------------------------------------------------------------------------
    # Load validation tables.
    # -------------------------------------------------------------------------

    section(
        "LOADING VALIDATION DATASETS"
    )

    tables = {}

    for name, path in FILES.items():

        # The main validation tables are loaded first.
        tables[name] = read_tsv(path)

    # -------------------------------------------------------------------------
    # Write schema report.
    # -------------------------------------------------------------------------

    section(
        "WRITING SCHEMA REPORT"
    )

    write_schema_report(
        tables
    )

    # -------------------------------------------------------------------------
    # Generate validation figures.
    # -------------------------------------------------------------------------

    section(
        "GENERATING VALIDATION PERFORMANCE FIGURES"
    )

    figure_01_similarity_threshold_recovery(
        tables["threshold_summary"]
    )

    figure_02_top_k_target_recovery(
        tables["target_recovery"]
    )

    figure_03_neighbor_recovery(
        tables["neighbor_recovery"]
    )

    figure_04_target_vs_offtarget(
        tables["target_recovery"],
        tables["offtarget_recovery"],
    )

    figure_05_target_ranking_performance(
        tables["target_recovery"]
    )

    figure_06_similarity_distribution(
        tables["target_recovery"]
    )

    figure_07_target_hierarchy_recovery(
        tables["target_recovery"]
    )

    figure_08_candidate_burden(
        tables["threshold_summary"]
    )

    figure_09_validation_summary(
        tables["validation_summary"]
    )

    figure_10_annotation_coverage(
        tables["target_annotation_qc"]
    )

    # -------------------------------------------------------------------------
    # Derived metrics.
    # -------------------------------------------------------------------------

    section(
        "CALCULATING DERIVED VALIDATION METRICS"
    )

    write_derived_metrics(
        tables["target_recovery"],
        tables["neighbor_recovery"],
        tables["offtarget_recovery"],
    )

    # -------------------------------------------------------------------------
    # Manifest.
    # -------------------------------------------------------------------------

    section(
        "WRITING MANIFEST"
    )

    write_manifest()

    # -------------------------------------------------------------------------
    # Final report.
    # -------------------------------------------------------------------------

    end = datetime.now().astimezone()

    section(
        "SCRIPT 08 v2 COMPLETE"
    )

    log(
        f"End time          : {end.isoformat()}"
    )

    log(
        f"Generated figures : {len(GENERATED)}"
    )

    log(
        f"Skipped figures   : {len(SKIPPED)}"
    )

    log(
        f"Errors            : {len(ERRORS)}"
    )

    if GENERATED:

        log("")
        log("GENERATED FIGURES:")

        for item in GENERATED:
            log(
                f"  {item['figure']}"
            )

    if SKIPPED:

        log("")
        log("SKIPPED FIGURES:")

        for item in SKIPPED:
            log(
                f"  {item}"
            )

    if ERRORS:

        log("")
        log("ERRORS:")

        for error in ERRORS:
            log(
                f"  {error}"
            )

    # -------------------------------------------------------------------------
    # Save complete log.
    # -------------------------------------------------------------------------

    log_path = OUTPUT_DIR / "08_target_offtarget_validation_figures.log"

    with open(
        log_path,
        "w",
        encoding="utf-8",
    ) as handle:

        handle.write(
            "\n".join(LOG_LINES)
        )

    print("")
    print(
        f"Log written to: {log_path}"
    )

    print(
        f"Output directory: {OUTPUT_DIR}"
    )

    return 0 if not ERRORS else 1


if __name__ == "__main__":
    sys.exit(
        main()
    )
